
#ifndef COCOS2D_H_
#define COCOS2D_H_

#include <string>
#include <vector>

class cocos2d {
public:
    void ccArrayNew(unsigned int);
    void ccDrawFree();
    void ccDrawInit();
    void ccDrawLine(cocos2d::CCPoint const&, cocos2d::CCPoint const&);
    void ccDrawPoly(cocos2d::CCPoint const*, unsigned int, bool);
    void ccDrawRect(cocos2d::CCPoint, cocos2d::CCPoint);
    void ccGLEnable(cocos2d::ccGLServerState);
    void ccpToAngle(cocos2d::CCPoint const&);
    void qChildSort(void const*, void const*);
    void tgaDestroy(cocos2d::sImageTGA*);
    void ccArrayFree(cocos2d::_ccArray*&);
    void ccCArrayNew(unsigned int);
    void ccDrawLines(cocos2d::CCPoint const*, unsigned int);
    void ccDrawPoint(cocos2d::CCPoint const&);
    void ccGLBindVAO(unsigned int);
    void ccPointSize(float);
    void ccpCompMult(cocos2d::CCPoint const&, cocos2d::CCPoint const&);
    void ccpDistance(cocos2d::CCPoint const&, cocos2d::CCPoint const&);
    void ccpForAngle(float);
    void ccpFromSize(cocos2d::CCSize const&);
    void unzOpen2_64(void const*, cocos2d::zlib_filefunc64_def_s*);
    void CCMessageBox(char const*, char const*);
    void CGAffineToGL(cocos2d::CCAffineTransform const*, float*);
    void GLToCGAffine(float const*, cocos2d::CCAffineTransform*);
    void call_zopen64(cocos2d::zlib_filefunc64_32_def_s const*, void const*, int);
    void call_zseek64(cocos2d::zlib_filefunc64_32_def_s const*, void*, unsigned long long, int);
    void call_ztell64(cocos2d::zlib_filefunc64_32_def_s const*, void*);
    void ccCArrayFree(cocos2d::_ccCArray*);
    void ccDrawCircle(cocos2d::CCPoint const&, float, float, unsigned int, bool);
    void ccDrawCircle(cocos2d::CCPoint const&, float, float, unsigned int, bool, float, float);
    void ccDrawPoints(cocos2d::CCPoint const*, unsigned int);
    void ccpNormalize(cocos2d::CCPoint const&);
    void tgaFlipImage(cocos2d::sImageTGA*);
    void unzGetOffset(void*);
    void unzSetOffset(void*, unsigned long);
    void _base64Decode(unsigned char const*, unsigned int, unsigned char*, unsigned int*, bool);
    void _base64Encode(unsigned char const*, unsigned int, char*, bool);
    void ccArrayShrink(cocos2d::_ccArray*);
    void ccDrawColor4B(unsigned char, unsigned char, unsigned char, unsigned char);
    void ccDrawColor4F(float, float, float, float);
    void ccGLBlendFunc(unsigned int, unsigned int);
    void ccpFuzzyEqual(cocos2d::CCPoint const&, cocos2d::CCPoint const&, float);
    void iscjk_unicode(unsigned short);
    void tgaLoadHeader(unsigned char*, unsigned long, cocos2d::sImageTGA*);
    void unzGetFilePos(void*, cocos2d::unz_file_pos_s*);
    void unzLocateFile(void*, char const*, int);
    void ccGLUseProgram(unsigned int);
    void cc_utf8_strlen(char const*);
    void ccpAngleSigned(cocos2d::CCPoint const&, cocos2d::CCPoint const&);
    void cocos2dVersion();
    void unzGetOffset64(void*);
    void unzGoToFilePos(void*, cocos2d::unz_file_pos_s*);
    void unzSetOffset64(void*, unsigned long long);
    void ccDrawSolidPoly(cocos2d::CCPoint const*, unsigned int, cocos2d::_ccColor4F);
    void ccDrawSolidRect(cocos2d::CCPoint, cocos2d::CCPoint, cocos2d::_ccColor4F);
    void cc_utf8_trim_ws(std::vector<unsigned short>*);
    void isspace_unicode(unsigned short);
    void unzGetFilePos64(void*, cocos2d::unz64_file_pos_s*);
    void unzGoToNextFile(void*);
    void CCRectFromString(char const*);
    void CCSizeFromString(char const*);
    void ccDrawCatmullRom(cocos2d::CCPointArray*, unsigned int);
    void ccDrawQuadBezier(cocos2d::CCPoint const&, cocos2d::CCPoint const&, cocos2d::CCPoint const&, unsigned int);
    void cc_utf16_to_utf8(unsigned short const*, int*);
    void cc_utf8_to_utf16(char const*, int*);
    void ccpLineIntersect(cocos2d::CCPoint const&, cocos2d::CCPoint const&, cocos2d::CCPoint const&, cocos2d::CCPoint const&, float*, float*);
    void ccpRotateByAngle(cocos2d::CCPoint const&, cocos2d::CCPoint const&, float);
    void tgaLoadImageData(unsigned char*, unsigned long, cocos2d::sImageTGA*);
    void unzGetGlobalInfo(void*, cocos2d::unz_global_info_s*);
    void unzGoToFilePos64(void*, cocos2d::unz64_file_pos_s const*);
    void unzGoToFirstFile(void*);
    void CCPointFromString(char const*);
    void FNTConfigLoadFile(char const*);
    void ccDrawCubicBezier(cocos2d::CCPoint const&, cocos2d::CCPoint const&, cocos2d::CCPoint const&, cocos2d::CCPoint const&, unsigned int);
    void ccGLBindTexture2D(unsigned int);
    void ccGLDeleteProgram(unsigned int);
    void ccGLDeleteTexture(unsigned int);
    void ccpIntersectPoint(cocos2d::CCPoint const&, cocos2d::CCPoint const&, cocos2d::CCPoint const&, cocos2d::CCPoint const&);
    void tgaRGBtogreyscale(cocos2d::sImageTGA*);
    void unzGoToNextFile64(void*, cocos2d::unz_file_info64_s*, char*, unsigned long);
    void ccArrayAppendArray(cocos2d::_ccArray*, cocos2d::_ccArray*);
    void ccArrayRemoveArray(cocos2d::_ccArray*, cocos2d::_ccArray*);
    void ccCardinalSplineAt(cocos2d::CCPoint&, cocos2d::CCPoint&, cocos2d::CCPoint&, cocos2d::CCPoint&, float, float);
    void ccDrawFilledCircle(cocos2d::CCPoint const&, float, float, unsigned int);
    void ccGLBindTexture2DN(unsigned int, unsigned int);
    void ccGLDeleteTextureN(unsigned int, unsigned int);
    void unzGetGlobalInfo64(void*, cocos2d::unz_global_info64_s*);
    void unzGoToFirstFile64(void*, cocos2d::unz_file_info64_s*, char*, unsigned long);
    void unzOpenCurrentFile(void*);
    void unzReadCurrentFile(void*, void*, unsigned int);
    void ccArrayAppendObject(cocos2d::_ccArray*, cocos2d::CCObject*);
    void ccArrayRemoveObject(cocos2d::_ccArray*, cocos2d::CCObject*, bool);
    void ccCArrayAppendArray(cocos2d::_ccCArray*, cocos2d::_ccCArray*);
    void ccCArrayAppendValue(cocos2d::_ccCArray*, void*);
    void ccCArrayRemoveArray(cocos2d::_ccCArray*, cocos2d::_ccCArray*);
    void ccCArrayRemoveValue(cocos2d::_ccCArray*, void*);
    void ccDrawCircleSegment(cocos2d::CCPoint const&, float, float, float, unsigned int, bool, float, float);
    void ccpSegmentIntersect(cocos2d::CCPoint const&, cocos2d::CCPoint const&, cocos2d::CCPoint const&, cocos2d::CCPoint const&);
    void fill_fopen_filefunc(cocos2d::zlib_filefunc_def_s*);
    void unzCloseCurrentFile(void*);
    void unzGetGlobalComment(void*, char*, unsigned long);
    void unzOpenCurrentFile2(void*, int*, int*, int);
    void unzOpenCurrentFile3(void*, int*, int*, int, char const*);
    void FNTConfigRemoveCache();
    void ccDrawCardinalSpline(cocos2d::CCPointArray*, float, unsigned int);
    void ccArrayContainsObject(cocos2d::_ccArray*, cocos2d::CCObject*);
    void ccArrayDoubleCapacity(cocos2d::_ccArray*);
    void ccCArrayContainsValue(cocos2d::_ccCArray*, void*);
    void ccGLBlendResetToCache();
    void ccVertexLineIntersect(float, float, float, float, float, float, float, float, float*);
    void ccVertexLineToPolygon(cocos2d::CCPoint*, float, cocos2d::_ccVertex2F*, unsigned int, unsigned int);
    void fill_fopen64_filefunc(cocos2d::zlib_filefunc64_def_s*);
    void unzGetCurrentFileInfo(void*, cocos2d::unz_file_info_s*, char*, unsigned long, void*, unsigned long, char*, unsigned long);
    void unzGetLocalExtrafield(void*, void*, unsigned int);
    void CCAffineTransformScale(cocos2d::CCAffineTransform const&, float, float);
    void ccArrayAppendObjectNew(cocos2d::_ccArray*, cocos2d::CCObject*);
    void ccArrayFullRemoveArray(cocos2d::_ccArray*, cocos2d::_ccArray*);
    void ccCArrayDoubleCapacity(cocos2d::_ccCArray*);
    void CCAffineTransformConcat(cocos2d::CCAffineTransform const&, cocos2d::CCAffineTransform const&);
    void CCAffineTransformInvert(cocos2d::CCAffineTransform const&);
    void CCAffineTransformRotate(cocos2d::CCAffineTransform const&, float);
    void __CCAffineTransformMake(float, float, float, float, float, float);
    void ccArrayFastRemoveObject(cocos2d::_ccArray*, cocos2d::CCObject*);
    void ccArrayGetIndexOfObject(cocos2d::_ccArray*, cocos2d::CCObject*);
    void ccArrayRemoveAllObjects(cocos2d::_ccArray*);
    void ccCArrayFullRemoveArray(cocos2d::_ccCArray*, cocos2d::_ccCArray*);
    void ccCArrayGetIndexOfValue(cocos2d::_ccCArray*, void*);
    void ccCArrayRemoveAllValues(cocos2d::_ccCArray*);
    void ccGLEnableVertexAttribs(unsigned int);
    void unzGetCurrentFileInfo64(void*, cocos2d::unz_file_info64_s*, char*, unsigned long, void*, unsigned long, char*, unsigned long);
    void ccArrayAppendObjectBatch(cocos2d::_ccArray*, cocos2d::CCObject*);
    void ccArrayAppendObjectChild(cocos2d::_ccArray*, cocos2d::CCObject*);
    void ccGLInvalidateStateCache();
    void unzStringFileNameCompare(char const*, char const*, int);
    void CCProfilingEndTimingBlock(char const*);
    void ccArrayRecreateNewIndexes(cocos2d::_ccArray*);
    void ccArrayUpdateChildIndexes(cocos2d::_ccArray*);
    void CCAffineTransformTranslate(cocos2d::CCAffineTransform const&, float, float);
    void CCRectApplyAffineTransform(cocos2d::CCRect const&, cocos2d::CCAffineTransform const&);
    void ccArrayEnsureExtraCapacity(cocos2d::_ccArray*, unsigned int);
    void ccArrayInsertObjectAtIndex(cocos2d::_ccArray*, cocos2d::CCObject*, unsigned int);
    void ccArrayRemoveObjectAtIndex(cocos2d::_ccArray*, unsigned int, bool);
    void ccCArrayInsertValueAtIndex(cocos2d::_ccCArray*, void*, unsigned int);
    void ccCArrayRemoveValueAtIndex(cocos2d::_ccCArray*, unsigned int);
    void ccSetProjectionMatrixDirty();
    void cc_utf8_find_last_not_char(std::vector<unsigned short> const&, unsigned short);
    void unzOpenCurrentFilePassword(void*, char const*);
    void CCProfilingBeginTimingBlock(char const*);
    void CCProfilingResetTimingBlock(char const*);
    void ccArrayRecreateChildIndexes(cocos2d::_ccArray*);
    void ccArraySwapObjectsAtIndexes(cocos2d::_ccArray*, unsigned int, unsigned int);
    void ccCArrayEnsureExtraCapacity(cocos2d::_ccCArray*, unsigned int);
    void cc_utf16_vec_from_utf16_str(unsigned short const*);
    void __CCSizeApplyAffineTransform(cocos2d::CCSize const&, cocos2d::CCAffineTransform const&);
    void ccArrayAppendArrayWithResize(cocos2d::_ccArray*, cocos2d::_ccArray*);
    void CCAffineTransformMakeIdentity();
    void __CCPointApplyAffineTransform(cocos2d::CCPoint const&, cocos2d::CCAffineTransform const&);
    void ccArrayAppendObjectWithResize(cocos2d::_ccArray*, cocos2d::CCObject*);
    void ccCArrayAppendArrayWithResize(cocos2d::_ccCArray*, cocos2d::_ccCArray*);
    void ccCArrayAppendValueWithResize(cocos2d::_ccCArray*, void*);
    void getCharacterCountInUTF8String(std::string const&);
    void unzGetCurrentFileZStreamPos64(void*);
    void ccArrayFastRemoveObjectAtIndex(cocos2d::_ccArray*, unsigned int);
    void ccCArrayFastRemoveValueAtIndex(cocos2d::_ccCArray*, unsigned int);
    void ccArrayInsertObjectAtIndexBatch(cocos2d::_ccArray*, cocos2d::CCObject*, unsigned int);
    void ccArrayRemoveObjectAtIndexBatch(cocos2d::_ccArray*, unsigned int, bool);
    void ccArrayRemoveObjectAtIndexChild(cocos2d::_ccArray*, unsigned int, bool);
    void ccArrayAppendObjectWithResizeNew(cocos2d::_ccArray*, cocos2d::CCObject*);
    void CCAffineTransformEqualToTransform(cocos2d::CCAffineTransform const&, cocos2d::CCAffineTransform const&);
    void ccArrayFastRemoveObjectAtIndexNew(cocos2d::_ccArray*, unsigned int);
    void ccArrayAppendObjectWithResizeBatch(cocos2d::_ccArray*, cocos2d::CCObject*);
    void ccArrayAppendObjectWithResizeChild(cocos2d::_ccArray*, cocos2d::CCObject*);
    void ccArrayFastRemoveObjectAtIndexChild(cocos2d::_ccArray*, unsigned int);
    void fill_zlib_filefunc64_32_def_from_filefunc32(cocos2d::zlib_filefunc64_32_def_s*, cocos2d::zlib_filefunc_def_s const*);
    void CCLog(char const*, ...);
    void clampf(float, float, float);
    void unzeof(void*);
    void ccpLerp(cocos2d::CCPoint const&, cocos2d::CCPoint const&, float);
    void tgaLoad(char const*);
    void unzOpen(char const*);
    void unztell(void*);
    void CCLuaLog(char const*);
    void ccpAngle(cocos2d::CCPoint const&, cocos2d::CCPoint const&);
    void ccpClamp(cocos2d::CCPoint const&, cocos2d::CCPoint const&, cocos2d::CCPoint const&);
    void unzClose(void*);
    void unzOpen2(char const*, cocos2d::zlib_filefunc_def_s*);
    void ccNextPOT(unsigned long);
    void cc_wcslen(unsigned short const*);
    void ccpCompOp(cocos2d::CCPoint const&, float (*)(float));
    void ccpLength(cocos2d::CCPoint const&);
    void unzOpen64(void const*);
    void unztell64(void*);

protected:
    int m_characterCountInUTF8String;

};

#endif // COCOS2D_H_
