// ============================================================
// EditorUI.h — Reconstructed from libcocos2dcpp.so symbols
// ============================================================

#ifndef EDITORUI_H_
#define EDITORUI_H_

#include "cocos2d.h"
#include <string>

class EditorUI {
public:
    virtual ~EditorUI();
    virtual ~EditorUI();
    virtual ~EditorUI();

    void createGlow();
    void createLoop();
    void editObject(cocos2d::CCObject*);
    void getModeBtn(char const*, int);
    void moveObject(GameObject*, cocos2d::CCPoint);
    void onPlayback(cocos2d::CCObject*);
    void onPlaytest(cocos2d::CCObject*);
    void onSettings(cocos2d::CCObject*);
    void shouldSnap(GameObject*);
    void toggleMode(cocos2d::CCObject*);
    void toggleSnap(cocos2d::CCObject*);
    void updateZoom(float);
    void applyOffset(GameObject*);
    void copyObjects(cocos2d::CCArray*, bool, bool);
    void deselectAll();
    void editObject2(cocos2d::CCObject*);
    void editObject3(cocos2d::CCObject*);
    void getNeighbor(int, cocos2d::CCPoint, GJSmartDirection, cocos2d::CCArray*);
    void onCopyState(cocos2d::CCObject*);
    void onDeleteAll(cocos2d::CCObject*);
    void onDuplicate(cocos2d::CCObject*);
    void onEditColor(cocos2d::CCObject*);
    void onGoToLayer(cocos2d::CCObject*);
    void onGroupDown(cocos2d::CCObject*);
    void onLockLayer(cocos2d::CCObject*);
    void scrollWheel(float, float);
    void toggleSwipe(cocos2d::CCObject*);
    void alignObjects(cocos2d::CCArray*, bool);
    void angleChanged(float);
    void ccTouchBegan(cocos2d::CCTouch*, cocos2d::CCEvent*);
    void ccTouchEnded(cocos2d::CCTouch*, cocos2d::CCEvent*);
    void ccTouchMoved(cocos2d::CCTouch*, cocos2d::CCEvent*);
    void createExtras(cocos2d::CCArray*);
    void createObject(int, cocos2d::CCPoint);
    void createPrefab(GJSmartTemplate*, std::string, int);
    void deleteObject(GameObject*, bool);
    void enableButton(CreateMenuItem*);
    void flipObjectsX(cocos2d::CCArray*);
    void flipObjectsY(cocos2d::CCArray*);
    void getCreateBtn(int, int);
    void getGroupInfo(GameObject*, cocos2d::CCArray*, int&, int&, int&);
    void getSnapAngle(GameObject*, cocos2d::CCArray*);
    void offsetForKey(int);
    void onDeleteInfo(cocos2d::CCObject*);
    void onFindObject(cocos2d::CCObject*);
    void onPasteColor(cocos2d::CCObject*);
    void onPasteState(cocos2d::CCObject*);
    void pasteObjects(std::string, bool, bool);
    void removeOffset(GameObject*);
    void scaleObjects(cocos2d::CCArray*, float, float, cocos2d::CCPoint, ObjectScaleType, bool);
    void selectObject(GameObject*, bool);
    void showMaxError();
    void toggleLockUI(bool);
    void updateSlider();
    void disableButton(CreateMenuItem*);
    void doCopyObjects(bool);
    void edgeForObject(int, int);
    void getTouchPoint(cocos2d::CCTouch*, cocos2d::CCEvent*);
    void moveGamelayer(cocos2d::CCPoint);
    void onColorFilter(cocos2d::CCObject*);
    void onDeselectAll(cocos2d::CCObject*);
    void onGroupSticky(cocos2d::CCObject*);
    void onToggleGuide(EffectGameObject*);
    void rotateObjects(cocos2d::CCArray*, float, cocos2d::CCPoint);
    void scaleXChanged(float, bool);
    void scaleYChanged(float, bool);
    void selectObjects(cocos2d::CCArray*, bool);
    void setupEditMenu();
    void sliderChanged(cocos2d::CCObject*);
    void updateButtons();
    void valueFromXPos(float);
    void xPosFromValue(float);
    void zoomGameLayer(bool);
    void createMoveMenu();
    void createOutlines(cocos2d::CCArray*);
    void deselectObject(GameObject*);
    void deselectObject();
    void doPasteInPlace(bool);
    void doPasteObjects(bool);
    void findSnapObject(cocos2d::CCPoint, float);
    void findSnapObject(cocos2d::CCArray*, float);
    void getGroupCenter(cocos2d::CCArray*, bool);
    void keyBackClicked();
    void moveForCommand(EditCommand);
    void moveObjectCall(EditCommand);
    void moveObjectCall(cocos2d::CCObject*);
    void onCreateButton(cocos2d::CCObject*);
    void onCreateObject(int);
    void onPasteInPlace(cocos2d::CCObject*);
    void onStickyToggle(cocos2d::CCObject*);
    void onStopPlaytest(cocos2d::CCObject*);
    void playCircleAnim(cocos2d::CCPoint, float, float);
    void redoLastAction(cocos2d::CCObject*);
    void replaceGroupID(GameObject*, int, int);
    void scaleXYChanged(float, float, bool);
    void selectBuildTab(int);
    void toggleFreeMove(cocos2d::CCObject*);
    void undoLastAction(cocos2d::CCObject*);
    void updateEditMenu();
    void FLAlert_Clicked(FLAlertLayer*, bool);
    void addSnapPosition(cocos2d::CCPoint);
    void assignNewGroups(bool);
    void canSelectObject(GameObject*);
    void clickOnPosition(cocos2d::CCPoint);
    void createRockBases(cocos2d::CCArray*);
    void createRockEdges(cocos2d::CCArray*);
    void findTriggerTest();
    void getCycledObject(cocos2d::CCArray*, bool);
    void getSimpleButton(std::string, void (cocos2d::CCObject::*)(cocos2d::CCObject*), cocos2d::CCMenu*);
    void getSpriteButton(char const*, void (cocos2d::CCObject::*)(cocos2d::CCObject*), cocos2d::CCMenu*, float);
    void getSpriteButton(char const*, void (cocos2d::CCObject::*)(cocos2d::CCObject*), cocos2d::CCMenu*, float, int, cocos2d::CCPoint);
    void getSpriteButton(cocos2d::CCSprite*, void (cocos2d::CCObject::*)(cocos2d::CCObject*), cocos2d::CCMenu*, float, int, cocos2d::CCPoint);
    void onGoToBaseLayer(cocos2d::CCObject*);
    void onGroupIDFilter(cocos2d::CCObject*);
    void onNewCustomItem(cocos2d::CCObject*);
    void onToggleTraceIn(GameObject*);
    void onUngroupSticky(cocos2d::CCObject*);
    void playtestStopped();
    void setupCreateMenu();
    void setupDeleteMenu();
    void smartTypeForKey(int);
    void transformObject(GameObject*, EditCommand, bool);
    void anchorPointMoved(cocos2d::CCPoint);
    void angleChangeBegin();
    void angleChangeEnded();
    void ccTouchCancelled(cocos2d::CCTouch*, cocos2d::CCEvent*);
    void convertToBaseKey(int);
    void createUndoObject(UndoCommand, bool);
    void editButtonUsable();
    void getSmartNeighbor(SmartGameObject*, cocos2d::CCPoint, GJSmartDirection, cocos2d::CCArray*);
    void getTransformNode();
    void onDeleteSelected(cocos2d::CCObject*);
    void onDeleteStartPos(cocos2d::CCObject*);
    void onSelectBuildTab(cocos2d::CCObject*);
    void onTargetIDChange(int);
    void onToggleTraceOut(EffectGameObject*);
    void playerTouchBegan(cocos2d::CCTouch*, cocos2d::CCEvent*);
    void playerTouchEnded(cocos2d::CCTouch*, cocos2d::CCEvent*);
    void scaleChangeBegin();
    void scaleChangeEnded();
    void setIDPopupClosed(SetIDPopup*, int);
    void showMaxCoinError();
    void songStateChanged();
    void transformObjects(cocos2d::CCArray*, cocos2d::CCPoint, float, float, float, float, float, float);
    void triggerSwipeMode();
    void updateCreateMenu(bool);
    void updateDeleteMenu();
    void colorSelectClosed(cocos2d::_ccColor3B);
    void colorSelectClosed(cocos2d::CCNode*);
    void createCustomItems();
    void createExtraObject(int, cocos2d::CCPoint, GameObject*, cocos2d::CCArray*, int, int);
    void editButton2Usable();
    void editObjectSpecial(int);
    void getGridSnappedPos(cocos2d::CCPoint);
    void getRandomStartKey(int);
    void getRelativeOffset(GameObject*);
    void getSmartObjectKey(int, GJSmartDirection);
    void getTransformState();
    void orderUpCustomItem(cocos2d::CCObject*);
    void reloadCustomItems();
    void showMaxBasicError();
    void updateGroupIDBtn2();
    void updatePlaybackBtn();
    void applySpecialOffset(cocos2d::CCPoint, GameObject*, cocos2d::CCPoint);
    void arrayContainsClass(cocos2d::CCArray*, int);
    void closeLiveHSVSelect();
    void dynamicGroupUpdate(bool);
    void getLimitedPosition(cocos2d::CCPoint);
    void getSelectedObjects();
    void onAssignNewGroupID();
    void onDeleteCustomItem(cocos2d::CCObject*);
    void recreateButtonTabs();
    void rotationforCommand(EditCommand);
    void shouldDeleteObject(GameObject*);
    void toggleEnableRotate(cocos2d::CCObject*);
    void updateGridNodeSize(int);
    void updateGridNodeSize();
    void updateGroupIDLabel();
    void updateScaleControl();
    void copyObjectsDetailed(cocos2d::CCArray*);
    void createEdgeForObject(GameObject*, int);
    void editorLayerForArray(cocos2d::CCArray*, bool);
    void findAndSelectObject(int, bool);
    void getEditColorTargets(ColorAction*&, ColorAction*&, EffectGameObject*&);
    void isSpecialSnapObject(int);
    void liveEditColorUsable();
    void orderDownCustomItem(cocos2d::CCObject*);
    void positionIsInSnapped(cocos2d::CCPoint);
    void selectObjectsInRect(cocos2d::CCRect);
    void transformObjectCall(EditCommand);
    void transformObjectCall(cocos2d::CCObject*);
    void updateDeleteButtons();
    void activateScaleControl(cocos2d::CCObject*);
    void centerCameraOnObject(GameObject*);
    void checkLiveColorSelect();
    void closeLiveColorSelect();
    void deselectObjectsColor();
    void onDeleteSelectedType(cocos2d::CCObject*);
    void onResetSpecialFilter(cocos2d::CCObject*);
    void onUpdateDeleteFilter(cocos2d::CCObject*);
    void processSelectObjects(cocos2d::CCArray*);
    void transformChangeBegin();
    void transformChangeEnded();
    void tryUpdateTimeMarkers();
    void updateStickyControls();
    void canAllowMultiActivate(GameObject*, cocos2d::CCArray*);
    void changeSelectedObjects(cocos2d::CCArray*, bool);
    void createExtrasForObject(int, GameObject*, cocos2d::CCArray*);
    void createNewKeyframeAnim();
    void deleteTypeFromObjects(int, cocos2d::CCArray*);
    void deselectTargetPortals();
    void editColorButtonUsable();
    void onToggleSelectedOrder(EffectGameObject*);
    void positionWithoutOffset(GameObject*);
    void setupTransformControl();
    void toggleDuplicateButton();
    void toggleObjectInfoLabel();
    void transformObjectsReset();
    void transformSkewXChanged(float);
    void transformSkewYChanged(float);
    void updateEditButtonColor(int, cocos2d::_ccColor3B);
    void updateEditColorButton();
    void updateObjectInfoLabel();
    void createUndoSelectObject(bool);
    void deactivateScaleControl();
    void selectAllWithDirection(bool);
    void showDeleteConfirmation();
    void spriteFromObjectString(std::string, bool, bool, int, cocos2d::CCArray*, cocos2d::CCArray*, GameObject*);
    void toggleEditObjectButton();
    void transformObjectsActive();
    void transformResetRotation();
    void transformScaleXChanged(float);
    void transformScaleYChanged(float);
    void updateTransformControl();
    void activateRotationControl(cocos2d::CCObject*);
    void getCreateMenuItemButton(cocos2d::CCSprite*, void (cocos2d::CCObject::*)(cocos2d::CCObject*), cocos2d::CCMenu*, float, int, cocos2d::CCPoint);
    void resetObjectEditorValues(cocos2d::CCArray*);
    void transformScaleXYChanged(float, float);
    void updateSpecialUIElements();
    void activateTransformControl(cocos2d::CCObject*);
    void isLiveColorSelectTrigger(GameObject*);
    void menuItemFromObjectString(std::string, int);
    void toggleSpecialEditButtons();
    void transformRestoreRotation();
    void transformRotationChanged(float);
    void addObjectsToSmartTemplate(GJSmartTemplate*, cocos2d::CCArray*);
    void deactivateRotationControl();
    void repositionObjectsToCenter(cocos2d::CCArray*, cocos2d::CCPoint, bool);
    void resetSelectedObjectsColor();
    void transformRotationXChanged(float);
    void transformRotationYChanged(float);
    void constrainGameLayerPosition(float, float);
    void constrainGameLayerPosition();
    void convertKeyBasedOnNeighbors(int, int, cocos2d::CCPoint, cocos2d::CCArray*);
    void createSmartObjectsFromType(int, cocos2d::CCArray*, bool, bool);
    void deactivateTransformControl();
    void showLiveColorSelectForMode(int);
    void processSmartObjectsFromType(int, cocos2d::CCArray*, cocos2d::CCArray*, cocos2d::CCArray*, cocos2d::CCArray*);
    void registerWithTouchDispatcher();
    void deleteSmartBlocksFromObjects(cocos2d::CCArray*);
    void checkDiffAfterTransformAnchor(cocos2d::CCPoint, cocos2d::CCArray*);
    void createSmartObjectsFromTemplate(GJSmartTemplate*, cocos2d::CCArray*, bool, bool, bool, bool);
    void showLiveColorSelectForModeSpecial(int);
    void draw();
    void init(LevelEditorLayer*);
    void getUI();
    void keyUp(cocos2d::enumKeyCodes, double);
    void create(LevelEditorLayer*);
    void onCopy(cocos2d::CCObject*);
    void showUI(bool);
    void zoomIn(cocos2d::CCObject*);
    void editHSV();
    void getXMin(int);
    void keyDown(cocos2d::enumKeyCodes, double);
    void onPaste(cocos2d::CCObject*);
    void onPause(cocos2d::CCObject*);
    void resetUI();
    void zoomOut(cocos2d::CCObject*);
    void onCreate();
    void onDelete(cocos2d::CCObject*);
    void editColor();
    void editGroup(cocos2d::CCObject*);
    void getButton(char const*, int, void (cocos2d::CCObject::*)(cocos2d::CCObject*), cocos2d::CCMenu*);
    void onGroupUp(cocos2d::CCObject*);
    void selectAll();

};

#endif // EDITORUI_H_
