// ============================================================
// FreeFunctions.h — Free functions from libcocos2dcpp.so
// ============================================================

#ifndef FREE_FUNCTIONS_H_
#define FREE_FUNCTIONS_H_

#include "cocos2d.h"
#include <string>
#include <vector>

void alignXSort(void const*, void const*);
void alignYSort(void const*, void const*);
void boxCompMax(void const*, void const*);
void boxCompMin(void const*, void const*);
void calculateK(float, float, float, float, float);
void compOrderY(void const*, void const*);
void formatTags(std::string const&);
void gen_random(int);
void getApkPath();
void matrixMult(float (*) [3], float (*) [3], float (*) [3]);
void smoothstep(float, float, float);
void uberShader();
void xCompSpeed(void const*, void const*);
void xRotateMat(float (*) [3], float, float);
void yRotateMat(float (*) [3], float, float);
void zRotateMat(float (*) [3], float, float);
void ERRCHECK_fn(FMOD_RESULT, char const*, int);
void boxCompMaxX(void const*, void const*);
void boxCompMinX(void const*, void const*);
void canDrawLine(int, int, std::unordered_set<unsigned long>, std::equal_to<unsigned long>, std::allocator<unsigned long> >&);
void cubicBezier(cocos2d::CCPoint const&, cocos2d::CCPoint const&, cocos2d::CCPoint const&, cocos2d::CCPoint const&, float);
void formatBytes(int);
void getDistance(cocos2d::CCPoint, cocos2d::CCPoint);
void getEventKey(int, int);
void isCharacter(char);
void limitCamera(cocos2d::CCPoint&, cocos2d::CCPoint, cocos2d::CCPoint);
void listCompare(void const*, void const*);
void mIDCompSort(GameObject* const&, GameObject* const&);
void mIDSaveSort(void const*, void const*);
void makeDrawKey(int, int);
void modifyValue(double);
void randomRange(cocos2d::CCPoint, float, float);
void rotatePoint(cocos2d::CCPoint&, float, cocos2d::CCPoint);
void songCompare(void const*, void const*);
void countSortAsc(CountTriggerAction const&, CountTriggerAction const&);
void countSortDec(CountTriggerAction const&, CountTriggerAction const&);
void getChannelID(FMOD::Channel*);
void getPageCount();
void hashRemapMap(std::unordered_map<int, int>, std::equal_to<int>, std::allocator<std::pair<const int, int> > > const&);
void levelCompare(void const*, void const*);
void processTrace(GameObject*, LevelEditorLayer*, std::vector<TraceDrawObject>&, bool);
void scoreCompare(void const*, void const*);
void sfxIDCompare(void const*, void const*);
void xCompRealPos(void const*, void const*);
void addStarsToMap(std::unordered_map<int, int>, std::equal_to<int>, std::allocator<std::pair<const int, int> > >&, std::string const&);
void artIconForKey(int, int);
void base64_decode(std::string const&);
void base64_encode(unsigned char const*, unsigned int);
void bgForGauntlet(GauntletType);
void compOrderXInv(void const*, void const*);
void compOrderYInv(void const*, void const*);
void drawLightning(cocos2d::CCPoint, cocos2d::CCPoint, int, int, unsigned long, cocos2d::CCPoint*, unsigned int*);
void getHoverValue(float, float, float, float);
void getNextRandom(unsigned long*);
void getRemappedID(int, RemapState const&);
void opKeyToString(int);
void printTheArray(int*, int);
void rotateCCPoint(cocos2d::CCPoint&, float, cocos2d::CCPoint);
void showDialogJNI(char const*, char const*);
void songIDCompare(void const*, void const*);
void spawnNodeComp(void const*, void const*);
void spawnNodeSort(DelayedSpawnNode* const&, DelayedSpawnNode* const&);
void xCompPosition(void const*, void const*);
void SquareDistance(float, float, float, float);
void compKeyframeID(void const*, void const*);
void compShadowCopy(void const*, void const*);
void compareStrings(std::string const&, std::string const&);
void getDpadSetting(int, bool);
void getItemVarName(int, int);
void groupIDCompare(void const*, void const*);
void initExtensions();
void mergeTwoRemaps(std::unordered_map<int, int>, std::equal_to<int>, std::allocator<std::pair<const int, int> > > const&, std::unordered_map<int, int>, std::equal_to<int>, std::allocator<std::pair<const int, int> > > const&);
void sfxNameCompare(void const*, void const*);
void compEnterEffect(void const*, void const*);
void compKeyToString(int);
void getCollisionKey(int const&, int const&);
void groupIDCompare2(void const*, void const*);
void offsetForStreak(ShipStreak, float);
void parseSpecialKey(int, int&, bool&, bool&);
void performMathSign(double, int);
void signKeyToString(int, bool);
void smartPrefabSort(void const*, void const*);
void snapRotation360(float&);
void songNameCompare(void const*, void const*);
void textForWraithID(int);
void truncatedFloat2(float);
void truncatedFloat3(float);
void zoomLevelToZoom(int);
void chanceObjCompare(ChanceObject const*, ChanceObject const*);
void darkColorForPath(int);
void generateBestHash(int, int, int, int, int, int, int, int);
void getBoolForKeyJNI(char const*, bool);
void localStorageFree();
void localStorageInit(char const*);
void premultiplyAlpha(float (*) [3], float);
void roundKeyToString(int, bool);
void savedListCompare(void const*, void const*);
void setBoolForKeyJNI(char const*, bool);
void sfxIDCompareDesc(void const*, void const*);
void sfxLengthCompare(void const*, void const*);
void songOrderCompare(void const*, void const*);
void swapAlphaChannel(unsigned int*, unsigned int);
void truncFloat2ToStr(float);
void truncFloat3ToStr(float);
void compAdvFollowSort(AdvancedFollowInstance const&, AdvancedFollowInstance const&);
void findNextHighestID(int, int, std::unordered_set<int>, std::equal_to<int>, std::allocator<int> >&);
void getFloatForKeyJNI(char const*, float);
void getFrameForStreak(ShipStreak, float);
void getPackageNameJNI();
void isLegalUTF8String(unsigned char const**, unsigned char const*);
void isSpecialItemType(int);
void lightColorForPath(int);
void optionsStrCompare(void const*, void const*);
void randRangeWeighted(float, float);
void savedLevelCompare(void const*, void const*);
void scoreCompareMoons(void const*, void const*);
void setFloatForKeyJNI(char const*, float);
void shouldModifyValue(int);
void splitCollisionKey(int const&, int&, int&);
void targetKeyToString(int);
void timerItemToString(TimerItem const&);
void triggerCompEffect(void const*, void const*);
void ConvertUTF16toUTF8(unsigned short const**, unsigned short const*, unsigned char**, unsigned char*, ConversionFlags);
void ConvertUTF32toUTF8(unsigned int const**, unsigned int const*, unsigned char**, unsigned char*, ConversionFlags);
void ConvertUTF8toUTF16(unsigned char const**, unsigned char const*, unsigned short**, unsigned short*, ConversionFlags);
void ConvertUTF8toUTF32(unsigned char const**, unsigned char const*, unsigned int**, unsigned int*, ConversionFlags);
void achievementCompare(void const*, void const*);
void compAdvancedFollow(void const*, void const*);
void getDistanceSquared(cocos2d::CCPoint, cocos2d::CCPoint);
void getDoubleForKeyJNI(char const*, double);
void getFramesForStreak(ShipStreak);
void getNumBytesForUTF8(unsigned char);
void getStringForKeyJNI(char const*, char const*);
void objectIsTraceValid(EffectGameObject*);
void saveAdvFollowSetup(AdvancedFollowTriggerObject*, std::vector<AdvFollowSetup>&, std::unordered_set<int>, std::equal_to<int>, std::allocator<int> >&);
void scoreCompareDemons(void const*, void const*);
void setDoubleForKeyJNI(char const*, double);
void setStringForKeyJNI(char const*, char const*);
void sfxNameCompareDesc(void const*, void const*);
void textSectionCompare(void const*, void const*);
void traceColorForIndex(int);
void yOffsetForGauntlet(GauntletType);
void ConvertUTF16toUTF32(unsigned short const**, unsigned short const*, unsigned int**, unsigned int*, ConversionFlags);
void ConvertUTF32toUTF16(unsigned int const**, unsigned int const*, unsigned short**, unsigned short*, ConversionFlags);
void applyPositionLimits(cocos2d::CCPoint&, GameObject*, GameObject*, GameObject*, GameObject*);
void compEnterEffectSort(EnterEffectInstance const&, EnterEffectInstance const&);
void customObjectCompare(void const*, void const*);
void getFileDirectoryJNI();
void getIntegerForKeyJNI(char const*, int);
void getUTF8StringLength(unsigned char const*);
void isLegalUTF8Sequence(unsigned char const*, unsigned char const*);
void isRelevantForPlayer(PlayerObject*, PlayerButtonCommand const&);
void isValidEmailAddress(char const*);
void localStorageGetItem(char const*);
void localStorageSetItem(char const*, char const*);
void prefabKeyFromBinary(std::string);
void processSFXGroupEdit(SFXTriggerState&, float, std::unordered_map<int, SFXValueState>, std::equal_to<int>, std::allocator<std::pair<const int, SFXValueState> > >&);
void setIntegerForKeyJNI(char const*, int);
void terminateProcessJNI();
void timerItemFromString(std::string const&);
void getSettingsForStreak(ShipStreak, PlayerObject*, float&, float&);
void getSettingsForStreak(ShipStreak, float, float, float&, float&);
void processTraceInSource(GameObject*, GameObject*, std::unordered_set<int>, std::equal_to<int>, std::allocator<int> >&, std::vector<std::vector<ChainNode>, std::allocator<std::vector<ChainNode> > >&, std::unordered_set<int>, std::equal_to<int>, std::allocator<int> >&, std::unordered_set<int>, std::equal_to<int>, std::allocator<int> >&, LevelEditorLayer*, std::vector<std::vector<ChainNode>, std::allocator<std::vector<ChainNode> > >&, std::unordered_set<int>, std::equal_to<int>, std::allocator<int> >&, std::unordered_map<int, std::vector<EffectGameObject*> >, std::hash<int>, std::equal_to<int>, std::allocator<std::pair<const int, std::vector<EffectGameObject*> > > >&, std::unordered_set<StateKey>, std::allocator<StateKey> >&, std::unordered_map<int, std::unordered_set<int>, std::equal_to<int>, std::allocator<int> >, std::hash<int>, std::equal_to<int>, std::allocator<std::pair<const int, std::unordered_set<int>, std::equal_to<int>, std::allocator<int> > > > >&, bool);
void sfxLengthCompareDesc(void const*, void const*);
void shouldModifyValueGPO(int);
void updateStreakSettings(cocos2d::CCMotionStreak*, ShipStreak, PlayerObject*);
void achievementStrCompare(void const*, void const*);
void getCurrentLanguageJNI();
void getFrameTimeForStreak(ShipStreak);
void isSpecialCurrencyType(CurrencySpriteType);
void processTraceOutSource(EffectGameObject*, GameObject*, std::unordered_set<int>, std::equal_to<int>, std::allocator<int> >&, std::vector<ChainNode>&, std::vector<std::vector<ChainNode>, std::allocator<std::vector<ChainNode> > >&, std::unordered_set<StateKey>, std::allocator<StateKey> >&, std::unordered_set<StateKey>, std::allocator<StateKey> >&, LevelEditorLayer*, RemapState const&, std::vector<std::vector<ChainNode>, std::allocator<std::vector<ChainNode> > >&, std::unordered_map<int, std::unordered_set<int>, std::equal_to<int>, std::allocator<int> >, std::hash<int>, std::equal_to<int>, std::allocator<std::pair<const int, std::unordered_set<int>, std::equal_to<int>, std::allocator<int> > > > >&, bool, bool, int);
void scoreCompareUserCoins(void const*, void const*);
void showEditTextDialogJNI(char const*, char const*, int, int, int, int, void (*)(char const*, void*), void*);
void deallocateDoubleNested(std::vector<std::vector<int>*, std::allocator<std::vector<int>*> >&);
void enableAccelerometerJNI();
void localStorageRemoveItem(char const*);
void shouldModifyEnterValue(int);
void addTargetIDsFromTrigger(EffectGameObject*, std::vector<int>&);
void colorRotationShaderBody();
void disableAccelerometerJNI();
void normalizeKeyframeValues(double&, double&, double&, double&);
void alphaNumericallyLessThan(char const*, char const*);
void generateAllBinaryStrings(int, int*, int, cocos2d::CCDictionary*, cocos2d::CCNode*);
void getStringWithEllipsisJni(char const*, float, float);
void nextRemapStateForTrigger(EffectGameObject*, RemapState const&, RemapState&);
void parseLevelLeaderboardKey(std::string, int&, int&, int&);
void deallocateDoubleNestedBool(std::vector<std::vector<bool>*, std::allocator<std::vector<bool>*> >&);
void getRotateCommandAngleDelta(EnhancedTriggerObject*, GameObject*, GameObject*, GameObject*, GameObject*, GameObject*, GameObject*, GameObject*);
void cc_assert_script_compatible(char const*);
void kerningSliderValueFromValue(int);
void kerningValueFromSliderValue(float);
void setAccelerometerIntervalJNI(float);
void getFontSizeAccordingHeightJni(int);
void lerp(cocos2d::CCPoint const&, cocos2d::CCPoint const&, float);
void xComp2(void const*, void const*);
void Slerp2D(float, float, float);
void mIDComp(void const*, void const*);
void mIDSort(void const*, void const*);
void ndigits(char const*);
void numComp(void const*, void const*);
void randInt(int, int);
void isNumber(char);
void random2d(cocos2d::CCPoint);
void vertTest();
void compOrder(void const*, void const*);
void drawArrow(cocos2d::CCDrawNode*, cocos2d::CCPoint const&, cocos2d::CCPoint const&, float, cocos2d::_ccColor4F);
void drawTrace(LevelEditorLayer*, std::vector<TraceDrawObject>&, bool, cocos2d::CCDrawNode*);
void hueMatrix(float (*) [3], float);
void isOpValid(int, float);
void normalize(cocos2d::CCPoint);
void randRange(float, float);
void xCompReal(void const*, void const*);
void __terminate_handler;
void __unexpected_handler;
void s_sharedFileUtils;
void urlAlphabet;
void sm_pSharedApplication;
void m_sFilePath;
void m_spUserDefault;
void m_sbIsFilePathInitialized;
void s_gSharedConfiguration;
void isReloading;
void textures;
void s_pSharedAnimationCache;
void ccExSwitchMask_frag;
void v3_pixel_formathash;
void ccPositionColor_frag;
void ccPositionColor_vert;
void ccPositionTexture_frag;
void ccPositionTexture_vert;
void ccPosition_uColor_frag;
void ccPosition_uColor_vert;
void CCAffineTransformIdentity;
void kCCProfilerCategorySprite;
void ccPositionTextureColor_frag;
void ccPositionTextureColor_vert;
void kCCProfilerCategoryParticles;
void ccPositionTextureA8Color_frag;
void ccPositionTextureA8Color_vert;
void ccPositionTexture_uColor_frag;
void ccPositionTexture_uColor_vert;
void kCCProfilerCategoryBatchSprite;
void ccPositionColorLengthTexture_frag;
void ccPositionColorLengthTexture_vert;
void ccPositionTextureColorAlphaTest_frag;
void s_uEncryptionKey;
void s_bEncryptionKeyIsValid;
void s_uEncryptedPvrKeyParts;
void alphabet;
void m_psJavaVM;
void operator delete[](void*);
void operator delete(void*);
void operator delete(void*, std::nothrow_t const&);
void operator new[](unsigned long);
void operator new[](unsigned long, std::nothrow_t const&);
void operator new(unsigned long);
void operator new(unsigned long, std::nothrow_t const&);

#endif // FREE_FUNCTIONS_H_
