// ============================================================
// GameLevelManager.h — Reconstructed from libcocos2dcpp.so symbols
// ============================================================

#ifndef GAMELEVELMANAGER_H_
#define GAMELEVELMANAGER_H_

#include "cocos2d.h"
#include <string>

class GameLevelManager {
public:
    virtual ~GameLevelManager();
    virtual ~GameLevelManager();
    virtual ~GameLevelManager();

    void dataLoaded(DS_Dictionary*);
    void firstSetup();
    void followUser(int);
    void getDailyID(GJTimedLevelType);
    void getDescKey(int);
    void getDiffKey(int);
    void getDiffVal(int);
    void handleItND(cocos2d::CCNode*, void*);
    void isDLActive(char const*);
    void setDiffVal(int, bool);
    void deleteLevel(GJGameLevel*);
    void getLevelKey(int);
    void getMapPacks(GJSearchObject*);
    void getPageInfo(char const*);
    void getTimeLeft(char const*, float);
    void getUserList(UserListType);
    void isTimeValid(char const*, float);
    void keyHasTimer(char const*);
    void reportLevel(int);
    void saveMapPack(GJMapPack*);
    void sharedState();
    void unblockUser(int);
    void updateLevel(GJGameLevel*);
    void uploadLevel(GJGameLevel*);
    void encodeDataTo(DS_Dictionary*);
    void getGJRewards(int);
    void getGauntlets();
    void getIntForKey(char const*);
    void getLengthStr(bool, bool, bool, bool, bool, bool);
    void getMainLevel(int, bool);
    void getReportKey(int);
    void hasLikedItem(LikeItemType, int, bool, int);
    void removeFriend(int);
    void restoreItems();
    void saveGauntlet(GJMapPack*);
    void setIntForKey(int, char const*);
    void unfollowUser(int);
    void addDLToActive(char const*);
    void deleteComment(int, CommentType, int);
    void downloadLevel(int, bool, int);
    void getBoolForKey(char const*);
    void getCommentKey(int, int, int, CommentKeyType);
    void getDailyTimer(GJTimedLevelType);
    void getFolderName(int, bool);
    void getGJUserInfo(int);
    void getLevelLists(GJSearchObject*);
    void getLocalLevel(int);
    void getMapPackKey(int);
    void getMessageKey(int);
    void getSavedLevel(GJGameLevel*);
    void getSavedLevel(int);
    void getTopArtists(int, int);
    void gotoLevelPage(GJGameLevel*);
    void hasRatedDemon(int);
    void isUpdateValid(int);
    void makeTimeStamp(char const*);
    void saveLevelList(GJLevelList*);
    void setBoolForKey(bool, char const*);
    void setFolderName(int, std::string, bool);
    void setLevelStars(int, int, bool);
    void storeUserInfo(GJUserScore*);
    void storeUserName(int, int, std::string);
    void uploadComment(std::string, CommentType, int, int);
    void createNewLevel();
    void createPageInfo(int, int, int);
    void getGauntletKey(int);
    void getLikeItemKey(LikeItemType, int, bool, int);
    void getMessagesKey(bool, int);
    void getSavedLevels(bool, int);
    void getSearchScene(char const*);
    void getUserInfoKey(int);
    void rateLevelAdmin(int, int, int, int, bool, bool);
    void resetAllTimers();
    void resetGauntlets();
    void responseToDict(std::string, bool);
    void saveLocalScore(int, int, int);
    void storeUserNames(std::string);
    void submitUserInfo();
    void tryGetUsername(int);
    void deleteLevelList(GJLevelList*);
    void getGJChallenges();
    void getLevelListKey(int);
    void getOnlineLevels(GJSearchObject*);
    void getRateStarsKey(int);
    void getSavedMapPack(int);
    void getUserMessages(bool, int, int);
    void handleItDelayed(bool, std::string, std::string, GJHttpType);
    void isFollowingUser(int);
    void likeFromLikeKey(char const*);
    void markItemAsLiked(LikeItemType, int, bool, int);
    void typeFromLikeKey(char const*);
    void updateUserScore();
    void updateUsernames();
    void uploadLevelList(GJLevelList*);
    void getActiveDailyID(GJTimedLevelType);
    void getDifficultyStr(bool, bool, bool, bool, bool, bool, bool, bool);
    void getLevelComments(int, int, int, int, CommentKeyType);
    void getLevelRateInfo(int);
    void getLevelSaveData();
    void getNextLevelName(std::string);
    void getSavedGauntlet(int);
    void getTopArtistsKey(int);
    void hasReportedLevel(int);
    void limitSavedLevels();
    void parseRestoreData(std::string);
    void resetTimerForKey(char const*);
    void setLevelFeatured(int, int, bool);
    void storeUserMessage(GJUserMessage*);
    void unrateLevelAdmin(int);
    void verifyLevelState(GJGameLevel*);
    void deleteServerLevel(int);
    void getAllUsedSongIDs();
    void getBasePostString();
    void getFriendRequests(bool, int, int);
    void getGJSecretReward(std::string);
    void getGauntletLevels(int);
    void getLeaderboardKey(LeaderboardType, LeaderboardStat);
    void getLocalLevelList(int);
    void getPostCommentKey(int);
    void getSavedLevelList(int);
    void getStoredUserList(UserListType);
    void hasDownloadedList(int);
    void itemIDFromLikeKey(char const*);
    void messageWasRemoved(int, bool);
    void purgeUnusedLevels();
    void readFriendRequest(int);
    void requestUserAccess();
    void saveFetchedLevels(cocos2d::CCArray*);
    void storeSearchResult(cocos2d::CCArray*, std::string, char const*);
    void suggestLevelStars(int, int, int);
    void updateDescription(int, std::string);
    void updateLevelOrders();
    void uploadUserMessage(int, std::string, std::string);
    void userNameForUserID(int);
    void ProcessHttpRequest(std::string, std::string, std::string, GJHttpType);
    void accountIDForUserID(int);
    void areGauntletsLoaded();
    void cleanupDailyLevels();
    void createAndGetLevels(std::string);
    void createAndGetScores(std::string, GJScoreType);
    void createNewLevelList();
    void deleteLevelComment(int, int);
    void deleteUserMessages(GJUserMessage*, cocos2d::CCArray*, bool);
    void getAccountComments(int, int, int);
    void getCompletedLevels(bool);
    void getSavedDailyLevel(int);
    void getSavedLevelLists(int);
    void getSplitIntFromKey(char const*, int);
    void hasDownloadedLevel(int);
    void hasRatedLevelStars(int);
    void invalidateMessages(bool, bool);
    void invalidateRequests(bool, bool);
    void invalidateUserList(UserListType, bool);
    void onBanUserCompleted(std::string, std::string);
    void onGetNewsCompleted(std::string, std::string);
    void pageFromCommentKey(char const*);
    void performNetworkTest();
    void removeDLFromActive(char const*);
    void removeUserFromList(int, UserListType);
    void specialFromLikeKey(char const*);
    void storeFriendRequest(GJFriendRequest*);
    void typeFromCommentKey(char const*);
    void updateLevelRewards(GJGameLevel*);
    void uploadLevelComment(int, std::string, int);
    void userIDForAccountID(int);
    void acceptFriendRequest(int, int);
    void createSmartTemplate();
    void deleteSmartTemplate(GJSmartTemplate*);
    void downloadUserMessage(int, bool);
    void getDeleteCommentKey(int, int, int);
    void getDeleteMessageKey(int, bool);
    void getFriendRequestKey(bool, int);
    void getLevelDownloadKey(int, bool, int);
    void getLevelLeaderboard(GJGameLevel*, LevelLeaderboardType, LevelLeaderboardMode);
    void getLocalLevelByName(std::string);
    void getLowestLevelOrder();
    void getStarLevelsString();
    void getUploadMessageKey(int);
    void hasLikedAccountItem(LikeItemType, int, bool, int);
    void markLevelAsReported(int);
    void onGetUsersCompleted(std::string, std::string);
    void onLikeItemCompleted(std::string, std::string);
    void resetStoredUserInfo(int);
    void resetStoredUserList(UserListType);
    void saveFetchedMapPacks(cocos2d::CCArray*);
    void storeCommentsResult(cocos2d::CCArray*, std::string, char const*);
    void uploadFriendRequest(int, std::string);
    void writeSpecialFilters(GJSearchObject*);
    void createAndGetMapPacks(std::string);
    void deleteAccountComment(int, int);
    void deleteFriendRequests(int, cocos2d::CCArray*, bool);
    void getAccountCommentKey(int, int);
    void getAllSmartTemplates();
    void getDemonLevelsString();
    void getGJDailyLevelState(GJTimedLevelType);
    void getGauntletSearchKey(int);
    void getHighestLevelOrder();
    void getLeaderboardScores(LeaderboardType, LeaderboardStat);
    void getStoredUserMessage(int);
    void markListAsDownloaded(int);
    void onBlockUserCompleted(std::string, std::string);
    void onRateDemonCompleted(std::string, std::string);
    void onRateStarsCompleted(std::string, std::string);
    void removeDelimiterChars(std::string, bool);
    void resetAccountComments(int);
    void resetDailyLevelState(GJTimedLevelType);
    void storeDailyLevelState(int, int, GJTimedLevelType);
    void updateLevelRankAdmin(int, int);
    void updateSavedLevelList(GJLevelList*);
    void uploadAccountComment(std::string);
    void userInfoForAccountID(int);
    void deleteServerLevelList(int);
    void getLikeAccountItemKey(LikeItemType, int, bool, int);
    void getNextFreeTemplateID();
    void getSavedGauntletLevel(int);
    void getStoredOnlineLevels(char const*);
    void hasLikedItemFullCheck(LikeItemType, int, int);
    void levelIDFromCommentKey(char const*);
    void markLevelAsDownloaded(int);
    void markLevelAsRatedDemon(int);
    void markLevelAsRatedStars(int);
    void saveFetchedLevelLists(cocos2d::CCArray*);
    void storeUserMessageReply(int, GJUserMessage*);
    void createAndGetLevelLists(std::string);
    void getActiveSmartTemplate();
    void getLevelLeaderboardKey(int, LevelLeaderboardType, LevelLeaderboardMode);
    void getStoredLevelComments(char const*);
    void onGetMapPacksCompleted(std::string, std::string);
    void onGetUserListCompleted(std::string, std::string);
    void onReportLevelCompleted(std::string, std::string);
    void onUnblockUserCompleted(std::string, std::string);
    void onUpdateLevelCompleted(std::string, std::string);
    void onUploadLevelCompleted(std::string, std::string);
    void setActiveSmartTemplate(GJSmartTemplate*);
    void deleteSentFriendRequest(int);
    void friendRequestWasRemoved(int, bool);
    void getCompletedDailyLevels();
    void getCompletedEventLevels(int, int);
    void hasDailyStateBeenLoaded(GJTimedLevelType);
    void onGetGJRewardsCompleted(std::string, std::string);
    void onGetGauntletsCompleted(std::string, std::string);
    void onRemoveFriendCompleted(std::string, std::string);
    void onRestoreItemsCompleted(std::string, std::string);
    void createAndGetCommentsFull(std::string, int, bool);
    void getCompletedWeeklyLevels();
    void onDeleteCommentCompleted(std::string, std::string);
    void onDownloadLevelCompleted(std::string, std::string);
    void onGetGJUserInfoCompleted(std::string, std::string);
    void onGetLevelListsCompleted(std::string, std::string);
    void onGetTopArtistsCompleted(std::string, std::string);
    void onSetLevelStarsCompleted(std::string, std::string);
    void onUploadCommentCompleted(std::string, std::string);
    void createAndGetLevelComments(std::string, int);
    void getStoredUserMessageReply(int);
    void levelIDFromPostCommentKey(char const*);
    void onRateLevelAdminCompleted(std::string, std::string);
    void onSubmitUserInfoCompleted(std::string, std::string);
    void friendRequestFromAccountID(int);
    void getCompletedGauntletDemons();
    void getCompletedGauntletLevels();
    void onGetGJChallengesCompleted(std::string, std::string);
    void onGetOnlineLevelsCompleted(std::string, std::string);
    void onGetUserMessagesCompleted(std::string, std::string);
    void onUpdateUserScoreCompleted(std::string, std::string);
    void onUploadLevelListCompleted(std::string, std::string);
    void createAndGetAccountComments(std::string, int);
    void onGetLevelCommentsCompleted(std::string, std::string);
    void onGetLevelRateInfoCompleted(std::string, std::string);
    void onGetLevelSaveDataCompleted(std::string, std::string);
    void onSetLevelFeaturedCompleted(std::string, std::string);
    void onDeleteServerLevelCompleted(std::string, std::string);
    void onGetFriendRequestsCompleted(std::string, std::string);
    void onGetGJSecretRewardCompleted(std::string, std::string);
    void onReadFriendRequestCompleted(std::string, std::string);
    void onRequestUserAccessCompleted(std::string, std::string);
    void onSuggestLevelStarsCompleted(std::string, std::string);
    void onUpdateDescriptionCompleted(std::string, std::string);
    void onUploadUserMessageCompleted(std::string, std::string);
    void resetCommentTimersForLevelID(int, CommentKeyType);
    void verifyContainerOnlyHasLevels(cocos2d::CCDictionary*);
    void getSavedDailyLevelFromLevelID(int);
    void onDeleteUserMessagesCompleted(std::string, std::string);
    void onGetAccountCommentsCompleted(std::string, std::string);
    void onProcessHttpRequestCompleted(cocos2d::extension::CCHttpClient*, cocos2d::extension::CCHttpResponse*);
    void onAcceptFriendRequestCompleted(std::string, std::string);
    void onDeleteFriendRequestCompleted(std::string, std::string);
    void onDownloadUserMessageCompleted(std::string, std::string);
    void onGetLevelLeaderboardCompleted(std::string, std::string);
    void onUploadFriendRequestCompleted(std::string, std::string);
    void resetCommentTimersForAccountID(int);
    void onGetGJDailyLevelStateCompleted(std::string, std::string);
    void onGetLeaderboardScoresCompleted(std::string, std::string);
    void processOnDownloadLevelCompleted(std::string, std::string, bool);
    void onDeleteServerLevelListCompleted(std::string, std::string);
    void removeLevelDownloadedKeysFromDict(cocos2d::CCDictionary*);
    void init();
    void banUser(int);
    void getNews();
    void getUsers(GJSearchObject*);
    void handleIt(bool, std::string, std::string, GJHttpType);
    void likeItem(LikeItemType, int, bool, int);
    void blockUser(int);
    void getLenKey(int);
    void getLenVal(int);
    void rateDemon(int, int, bool);
    void rateStars(int, int);
    void saveLevel(GJGameLevel*);
    void setLenVal(int, bool);

};

#endif // GAMELEVELMANAGER_H_
