
#ifndef GAMEMANAGER_H_
#define GAMEMANAGER_H_

#include "cocos2d.h"
#include <string>

class GameManager : public cocos2d::CCNode {
public:
    static GameManager* create();
    virtual ~GameManager();

    void addToGJLog(cocos2d::CCString*);
    void clearGJLog();
    void dataLoaded(DS_Dictionary*);
    void joinReddit();
    void keyForIcon(int, int);
    void loadGround(int);
    void printGJLog();
    void reloadMenu();
    void reorderKey(int, bool);
    void subYouTube();
    void tryCacheAd();
    void unloadIcon(int, int, int);
    void unlockIcon(int, IconType);
    void colorForIdx(int);
    void colorForPos(int);
    void doQuickSave();
    void fadeInMusic(std::string);
    void getFontFile(int);
    void getGTexture(int);
    void joinDiscord();
    void resumeAudio();
    void saveAdTimer();
    GameManager* sharedState();
    void startUpdate();
    void unloadIcons(int);
    void unlockColor(int, UnlockType);
    void updateMusic();
    int countForType(IconType);
    void encodeDataTo(DS_Dictionary*);
    void followTwitch();
    void getBGTexture(int);
    void getMGTexture(int);
    bool isIconLoaded(int, int);
    void likeFacebook();
    void resetAdTimer();
    void safePopScene();
    void followTwitter();
    void itemPurchased(char const*);
    void loadIconAsync(int, int, int, cocos2d::CCObject*);
    void playMenuMusic();
    void resetAllIcons();
    void videoAdHidden();
    void videoAdShowed();
    void checkUsedIcons();
    void getFontTexture(int);
    std::string getNextUsedKey(int, bool);
    bool isIconUnlocked(int, IconType);
    void levelIsPremium(int, int);
    void loadBackground(int);
    void loadDPadLayout(int, bool);
    void playSFXTrigger(SFXTriggerGameObject*);
    void reloadAllStep2();
    void reloadAllStep3();
    void reloadAllStep4();
    void reloadAllStep5();
    void saveDPadLayout(int, bool);
    void shortenAdTimer(float);
    void showMainMenuAd();
    void addIconDelegate(cocos2d::CCObject*, int);
    void fadeInMenuMusic();
    void getGameVariable(char const*);
    bool isColorUnlocked(int, UnlockType);
    void loadDeathEffect(int);
    void loadGroundAsync(int);
    void openEditorGuide();
    void queueReloadMenu();
    void setGameVariable(char const*, bool);
    void unlockedPremium();
    void updateCustomFPS();
    void addGameAnimation(int, int, float, std::string, std::string, int);
    void didExitPlayscene();
    void getIconRequestID();
    void getMenuMusicFile();
    void loadMiddleground(int);
    void recountUserStats(std::string);
    void resetAchievement(std::string);
    void resetCoinUnlocks();
    void resolutionForKey(int);
    void sheetNameForIcon(int, int);
    void showInterstitial();
    void switchScreenMode(bool, bool, bool, bool);
    void unloadBackground();
    void activeIconForType(IconType);
    void iconAndTypeForKey(int, int&, int&);
    void loadVideoSettings();
    void logLoadedIconInfo();
    void resetDPadSettings(bool);
    void returnToLastScene(GJGameLevel*);
    void verifyCoinUnlocks();
    void verifyStarUnlocks();
    void verifySyncedCoins();
    void addNewCustomObject(std::string);
    void claimItemsResponse(std::string);
    void dpadConfigToString(UIButtonConfig&);
    void eventUnlockFeature(char const*);
    void framesForAnimation(int);
    void getIntGameVariable(char const*);
    void loadDpadFromString(UIButtonConfig&, std::string);
    void removeCustomObject(int);
    void removeIconDelegate(int);
    void resumeAudioDelayed();
    void setIntGameVariable(char const*, int);
    void toggleGameVariable(char const*);
    void loadBackgroundAsync(int);
    void prepareDPadSettings();
    void rewardedVideoHidden();
    void setupGameAnimations();
    void switchCustomObjects(int, int);
    void tryShowInterstitial(int, int, int);
    void accountStatusChanged();
    bool canShowRewardedVideo();
    void completedAchievement(std::string);
    void generateSecretNumber();
    void getPracticeMusicFile();
    void iconTypeToUnlockType(IconType);
    void unlockTypeToIconType(int);
    void addDuplicateLastFrame(int);
    void finishedLoadingGAsync(int);
    void frameTimeForAnimation(int);
    void loadMiddlegroundAsync(int);
    void stringForCustomObject(int);
    void finishedLoadingBGAsync(cocos2d::CCObject*);
    void finishedLoadingGAsync1(cocos2d::CCObject*);
    void finishedLoadingGAsync2(cocos2d::CCObject*);
    void finishedLoadingMGAsync(int);
    std::string getNextUniqueObjectKey();
    bool shouldShowInterstitial(int, int, int);
    void showInterstitialForced();
    void addCustomAnimationFrame(int, int, std::string, std::string);
    void finishedLoadingMGAsync1(cocos2d::CCObject*);
    void finishedLoadingMGAsync2(cocos2d::CCObject*);
    void getUnlockForAchievement(std::string, int&, UnlockType&);
    void groundHasSecondaryColor(int);
    void reportAchievementWithID(char const*, int, bool);
    void rewardedVideoAdFinished(int);
    void calculateBaseKeyForIcons();
    void defaultFrameForAnimation(int);
    void finishedLoadingIconAsync(cocos2d::CCObject*);
    void reportPercentageForLevel(int, int, bool);
    void syncPlatformAchievements();
    void verifyAchievementUnlocks();
    std::string getOrderedCustomObjectKeys();
    void rewardedVideoHiddenDelayed();
    void checkSteamAchievementUnlock();
    void applicationDidEnterBackground();
    void applicationWillEnterForeground();
    bool init() override;
    void getUGV(char const*);
    void setUGV(char const*, bool);
    void update(float) override;
    void iconKey(int, IconType);
    void colorKey(int, UnlockType);
    void loadFont(int);
    void loadIcon(int, int, int);
    void lockIcon(int, IconType);
    void rateGame();
    void firstLoad();
    void lockColor(int, UnlockType);
    void reloadAll(bool, bool, bool, bool, bool);

protected:
    bool m_gamePlayEnabled;
    int m_iconRequestID;
    float m_musicVolume;
    std::string m_nextUniqueObjectKey;
    std::string m_nextUsedKey;
    std::string m_orderedCustomObjectKeys;
    int m_playerBallID;
    int m_playerBirdID;
    int m_playerColorPrimary;
    int m_playerColorSecondary;
    int m_playerDeathEffectID;
    int m_playerFrameID;
    int m_playerIconID;
    std::string m_playerName;
    int m_playerRobotID;
    int m_playerShipID;
    int m_playerSpiderID;
    int m_playerStreakID;
    int m_playerSwingID;
    int m_playerUserID;
    float m_sfxVolume;
    bool m_smoothFix;

};

#endif // GAMEMANAGER_H_
