
#ifndef GAMELEVELMANAGER_H_
#define GAMELEVELMANAGER_H_

#include "cocos2d.h"
#include <string>

class GameLevelManager : public cocos2d::CCNode {
public:
    static GameLevelManager* create();
    virtual ~GameLevelManager();

    void dataLoaded(DS_Dictionary*);
    void firstSetup();
    void followUser(int);
    void getDailyID(GJTimedLevelType);
    std::string getDescKey(int);
    std::string getDiffKey(int);
    void getDiffVal(int);
    void handleItND(cocos2d::CCNode*, void*);
    bool isDLActive(char const*);
    void setDiffVal(int, bool);
    void deleteLevel(GJGameLevel*);
    std::string getLevelKey(int);
    void getMapPacks(GJSearchObject*);
    void getPageInfo(char const*);
    void getTimeLeft(char const*, float);
    void getUserList(UserListType);
    bool isTimeValid(char const*, float);
    void keyHasTimer(char const*);
    void reportLevel(int);
    void saveMapPack(GJMapPack*);
    GameLevelManager* sharedState();
    void unblockUser(int);
    void updateLevel(GJGameLevel*);
    void uploadLevel(GJGameLevel*);
    void encodeDataTo(DS_Dictionary*);
    void getGJRewards(int);
    void getGauntlets();
    std::string getIntForKey(char const*);
    void getLengthStr(bool, bool, bool, bool, bool, bool);
    void getMainLevel(int, bool);
    std::string getReportKey(int);
    bool hasLikedItem(LikeItemType, int, bool, int);
    void removeFriend(int);
    void restoreItems();
    void saveGauntlet(GJMapPack*);
    void setIntForKey(int, char const*);
    void unfollowUser(int);
    void addDLToActive(char const*);
    void deleteComment(int, CommentType, int);
    void downloadLevel(int, bool, int);
    std::string getBoolForKey(char const*);
    std::string getCommentKey(int, int, int, CommentKeyType);
    void getDailyTimer(GJTimedLevelType);
    std::string getFolderName(int, bool);
    void getGJUserInfo(int);
    void getLevelLists(GJSearchObject*);
    void getLocalLevel(int);
    std::string getMapPackKey(int);
    std::string getMessageKey(int);
    std::string getSavedLevel(GJGameLevel*);
    std::string getSavedLevel(int);
    void getTopArtists(int, int);
    void gotoLevelPage(GJGameLevel*);
    bool hasRatedDemon(int);
    bool isUpdateValid(int);
    void makeTimeStamp(char const*);
    void saveLevelList(GJLevelList*);
    void setBoolForKey(bool, char const*);
    void setFolderName(int, std::string, bool);
    void setLevelStars(int, int, bool);
    void storeUserInfo(GJUserScore*);
    void storeUserName(int, int, std::string);
    void uploadComment(std::string, CommentType, int, int);
    GameLevelManager* createNewLevel();
    GameLevelManager* createPageInfo(int, int, int);
    std::string getGauntletKey(int);
    std::string getLikeItemKey(LikeItemType, int, bool, int);
    std::string getMessagesKey(bool, int);
    std::string getSavedLevels(bool, int);
    void getSearchScene(char const*);
    std::string getUserInfoKey(int);
    void rateLevelAdmin(int, int, int, int, bool, bool);
    void resetAllTimers();
    void resetGauntlets();
    void responseToDict(std::string, bool);
    void saveLocalScore(int, int, int);
    void storeUserNames(std::string);
    void submitUserInfo();
    void tryGetUsername(int);
    void deleteLevelList(GJLevelList*);
    void getGJChallenges();
    std::string getLevelListKey(int);
    void getOnlineLevels(GJSearchObject*);
    std::string getRateStarsKey(int);
    std::string getSavedMapPack(int);
    void getUserMessages(bool, int, int);
    void handleItDelayed(bool, std::string, std::string, GJHttpType);
    bool isFollowingUser(int);
    void likeFromLikeKey(char const*);
    void markItemAsLiked(LikeItemType, int, bool, int);
    void typeFromLikeKey(char const*);
    void updateUserScore();
    void updateUsernames();
    void uploadLevelList(GJLevelList*);
    void getActiveDailyID(GJTimedLevelType);
    void getDifficultyStr(bool, bool, bool, bool, bool, bool, bool, bool);
    void getLevelComments(int, int, int, int, CommentKeyType);
    void getLevelRateInfo(int);
    std::string getLevelSaveData();
    std::string getNextLevelName(std::string);
    std::string getSavedGauntlet(int);
    std::string getTopArtistsKey(int);
    bool hasReportedLevel(int);
    void limitSavedLevels();
    void parseRestoreData(std::string);
    void resetTimerForKey(char const*);
    void setLevelFeatured(int, int, bool);
    void storeUserMessage(GJUserMessage*);
    void unrateLevelAdmin(int);
    void verifyLevelState(GJGameLevel*);
    void deleteServerLevel(int);
    void getAllUsedSongIDs();
    void getBasePostString();
    void getFriendRequests(bool, int, int);
    void getGJSecretReward(std::string);
    void getGauntletLevels(int);
    std::string getLeaderboardKey(LeaderboardType, LeaderboardStat);
    void getLocalLevelList(int);
    std::string getPostCommentKey(int);
    std::string getSavedLevelList(int);
    void getStoredUserList(UserListType);
    bool hasDownloadedList(int);
    void itemIDFromLikeKey(char const*);
    void messageWasRemoved(int, bool);
    void purgeUnusedLevels();
    void readFriendRequest(int);
    void requestUserAccess();
    void saveFetchedLevels(cocos2d::CCArray*);
    void storeSearchResult(cocos2d::CCArray*, std::string, char const*);
    void suggestLevelStars(int, int, int);
    void updateDescription(int, std::string);
    void updateLevelOrders();
    void uploadUserMessage(int, std::string, std::string);
    void userNameForUserID(int);
    void ProcessHttpRequest(std::string, std::string, std::string, GJHttpType);
    void accountIDForUserID(int);
    bool areGauntletsLoaded();
    void cleanupDailyLevels();
    GameLevelManager* createAndGetLevels(std::string);
    GameLevelManager* createAndGetScores(std::string, GJScoreType);
    GameLevelManager* createNewLevelList();
    void deleteLevelComment(int, int);
    void deleteUserMessages(GJUserMessage*, cocos2d::CCArray*, bool);
    void getAccountComments(int, int, int);
    void getCompletedLevels(bool);
    std::string getSavedDailyLevel(int);
    std::string getSavedLevelLists(int);
    std::string getSplitIntFromKey(char const*, int);
    bool hasDownloadedLevel(int);
    bool hasRatedLevelStars(int);
    void invalidateMessages(bool, bool);
    void invalidateRequests(bool, bool);
    void invalidateUserList(UserListType, bool);
    void onBanUserCompleted(std::string, std::string);
    void onGetNewsCompleted(std::string, std::string);
    void pageFromCommentKey(char const*);
    void performNetworkTest();
    void removeDLFromActive(char const*);
    void removeUserFromList(int, UserListType);
    void specialFromLikeKey(char const*);
    void storeFriendRequest(GJFriendRequest*);
    void typeFromCommentKey(char const*);
    void updateLevelRewards(GJGameLevel*);
    void uploadLevelComment(int, std::string, int);
    void userIDForAccountID(int);
    void acceptFriendRequest(int, int);
    GameLevelManager* createSmartTemplate();
    void deleteSmartTemplate(GJSmartTemplate*);
    void downloadUserMessage(int, bool);
    std::string getDeleteCommentKey(int, int, int);
    std::string getDeleteMessageKey(int, bool);
    std::string getFriendRequestKey(bool, int);
    std::string getLevelDownloadKey(int, bool, int);
    void getLevelLeaderboard(GJGameLevel*, LevelLeaderboardType, LevelLeaderboardMode);
    std::string getLocalLevelByName(std::string);
    void getLowestLevelOrder();
    std::string getStarLevelsString();
    std::string getUploadMessageKey(int);
    bool hasLikedAccountItem(LikeItemType, int, bool, int);
    void markLevelAsReported(int);
    void onGetUsersCompleted(std::string, std::string);
    void onLikeItemCompleted(std::string, std::string);
    void resetStoredUserInfo(int);
    void resetStoredUserList(UserListType);
    void saveFetchedMapPacks(cocos2d::CCArray*);
    void storeCommentsResult(cocos2d::CCArray*, std::string, char const*);
    void uploadFriendRequest(int, std::string);
    void writeSpecialFilters(GJSearchObject*);
    GameLevelManager* createAndGetMapPacks(std::string);
    void deleteAccountComment(int, int);
    void deleteFriendRequests(int, cocos2d::CCArray*, bool);
    std::string getAccountCommentKey(int, int);
    void getAllSmartTemplates();
    std::string getDemonLevelsString();
    void getGJDailyLevelState(GJTimedLevelType);
    std::string getGauntletSearchKey(int);
    void getHighestLevelOrder();
    void getLeaderboardScores(LeaderboardType, LeaderboardStat);
    void getStoredUserMessage(int);
    void markListAsDownloaded(int);
    void onBlockUserCompleted(std::string, std::string);
    void onRateDemonCompleted(std::string, std::string);
    void onRateStarsCompleted(std::string, std::string);
    void removeDelimiterChars(std::string, bool);
    void resetAccountComments(int);
    void resetDailyLevelState(GJTimedLevelType);
    void storeDailyLevelState(int, int, GJTimedLevelType);
    void updateLevelRankAdmin(int, int);
    void updateSavedLevelList(GJLevelList*);
    void uploadAccountComment(std::string);
    void userInfoForAccountID(int);
    void deleteServerLevelList(int);
    std::string getLikeAccountItemKey(LikeItemType, int, bool, int);
    void getNextFreeTemplateID();
    std::string getSavedGauntletLevel(int);
    void getStoredOnlineLevels(char const*);
    bool hasLikedItemFullCheck(LikeItemType, int, int);
    void levelIDFromCommentKey(char const*);
    void markLevelAsDownloaded(int);
    void markLevelAsRatedDemon(int);
    void markLevelAsRatedStars(int);
    void saveFetchedLevelLists(cocos2d::CCArray*);
    void storeUserMessageReply(int, GJUserMessage*);
    GameLevelManager* createAndGetLevelLists(std::string);
    void getActiveSmartTemplate();
    std::string getLevelLeaderboardKey(int, LevelLeaderboardType, LevelLeaderboardMode);
    void getStoredLevelComments(char const*);
    void onGetMapPacksCompleted(std::string, std::string);
    void onGetUserListCompleted(std::string, std::string);
    void onReportLevelCompleted(std::string, std::string);
    void onUnblockUserCompleted(std::string, std::string);
    void onUpdateLevelCompleted(std::string, std::string);
    void onUploadLevelCompleted(std::string, std::string);
    void setActiveSmartTemplate(GJSmartTemplate*);
    void deleteSentFriendRequest(int);
    void friendRequestWasRemoved(int, bool);
    void getCompletedDailyLevels();
    void getCompletedEventLevels(int, int);
    bool hasDailyStateBeenLoaded(GJTimedLevelType);
    void onGetGJRewardsCompleted(std::string, std::string);
    void onGetGauntletsCompleted(std::string, std::string);
    void onRemoveFriendCompleted(std::string, std::string);
    void onRestoreItemsCompleted(std::string, std::string);
    GameLevelManager* createAndGetCommentsFull(std::string, int, bool);
    void getCompletedWeeklyLevels();
    void onDeleteCommentCompleted(std::string, std::string);
    void onDownloadLevelCompleted(std::string, std::string);
    void onGetGJUserInfoCompleted(std::string, std::string);
    void onGetLevelListsCompleted(std::string, std::string);
    void onGetTopArtistsCompleted(std::string, std::string);
    void onSetLevelStarsCompleted(std::string, std::string);
    void onUploadCommentCompleted(std::string, std::string);
    GameLevelManager* createAndGetLevelComments(std::string, int);
    void getStoredUserMessageReply(int);
    void levelIDFromPostCommentKey(char const*);
    void onRateLevelAdminCompleted(std::string, std::string);
    void onSubmitUserInfoCompleted(std::string, std::string);
    void friendRequestFromAccountID(int);
    void getCompletedGauntletDemons();
    void getCompletedGauntletLevels();
    void onGetGJChallengesCompleted(std::string, std::string);
    void onGetOnlineLevelsCompleted(std::string, std::string);
    void onGetUserMessagesCompleted(std::string, std::string);
    void onUpdateUserScoreCompleted(std::string, std::string);
    void onUploadLevelListCompleted(std::string, std::string);
    GameLevelManager* createAndGetAccountComments(std::string, int);
    void onGetLevelCommentsCompleted(std::string, std::string);
    void onGetLevelRateInfoCompleted(std::string, std::string);
    void onGetLevelSaveDataCompleted(std::string, std::string);
    void onSetLevelFeaturedCompleted(std::string, std::string);
    void onDeleteServerLevelCompleted(std::string, std::string);
    void onGetFriendRequestsCompleted(std::string, std::string);
    void onGetGJSecretRewardCompleted(std::string, std::string);
    void onReadFriendRequestCompleted(std::string, std::string);
    void onRequestUserAccessCompleted(std::string, std::string);
    void onSuggestLevelStarsCompleted(std::string, std::string);
    void onUpdateDescriptionCompleted(std::string, std::string);
    void onUploadUserMessageCompleted(std::string, std::string);
    void resetCommentTimersForLevelID(int, CommentKeyType);
    void verifyContainerOnlyHasLevels(cocos2d::CCDictionary*);
    std::string getSavedDailyLevelFromLevelID(int);
    void onDeleteUserMessagesCompleted(std::string, std::string);
    void onGetAccountCommentsCompleted(std::string, std::string);
    void onProcessHttpRequestCompleted(cocos2d::extension::CCHttpClient*, cocos2d::extension::CCHttpResponse*);
    void onAcceptFriendRequestCompleted(std::string, std::string);
    void onDeleteFriendRequestCompleted(std::string, std::string);
    void onDownloadUserMessageCompleted(std::string, std::string);
    void onGetLevelLeaderboardCompleted(std::string, std::string);
    void onUploadFriendRequestCompleted(std::string, std::string);
    void resetCommentTimersForAccountID(int);
    void onGetGJDailyLevelStateCompleted(std::string, std::string);
    void onGetLeaderboardScoresCompleted(std::string, std::string);
    void processOnDownloadLevelCompleted(std::string, std::string, bool);
    void onDeleteServerLevelListCompleted(std::string, std::string);
    void removeLevelDownloadedKeysFromDict(cocos2d::CCDictionary*);
    bool init() override;
    void banUser(int);
    void getNews();
    void getUsers(GJSearchObject*);
    void handleIt(bool, std::string, std::string, GJHttpType);
    void likeItem(LikeItemType, int, bool, int);
    void blockUser(int);
    std::string getLenKey(int);
    void getLenVal(int);
    void rateDemon(int, int, bool);
    void rateStars(int, int);
    void saveLevel(GJGameLevel*);
    void setLenVal(int, bool);

protected:
    cocos2d::CCDictionary* m_GJLevelScore;
    std::string m_accountCommentKey;
    int m_activeDailyID;
    bool m_activeSmartTemplate;
    int m_allUsedSongIDs;
    std::string m_basePostString;
    std::string m_boolForKey;
    std::string m_commentKey;
    int m_dailyID;
    int m_dailyLevelID;
    std::string m_deleteCommentKey;
    std::string m_deleteMessageKey;
    std::string m_demonLevelsString;
    std::string m_descKey;
    std::string m_diffKey;
    std::string m_folderName;
    std::string m_friendRequestKey;
    std::string m_gauntletKey;
    std::string m_gauntletSearchKey;
    std::string m_intForKey;
    std::string m_leaderboardKey;
    std::string m_lenKey;
    std::string m_levelDownloadKey;
    std::string m_levelKey;
    std::string m_levelLeaderboardKey;
    std::string m_levelListKey;
    float m_levelRateInfo;
    std::string m_likeAccountItemKey;
    std::string m_likeItemKey;
    std::string m_localLevelByName;
    std::string m_mapPackKey;
    std::string m_messageKey;
    std::string m_messagesKey;
    int m_nextFreeTemplateID;
    std::string m_nextLevelName;
    cocos2d::CCDictionary* m_onlineLevels;
    std::string m_postCommentKey;
    float m_rateStarsKey;
    std::string m_reportKey;
    int m_savedDailyLevelFromLevelID;
    cocos2d::CCDictionary* m_savedLevels;
    std::string m_splitIntFromKey;
    std::string m_starLevelsString;
    cocos2d::CCDictionary* m_storedLevels;
    std::string m_topArtistsKey;
    std::string m_uploadMessageKey;
    std::string m_userInfoKey;
    int m_weeklyLevelID;

};

#endif // GAMELEVELMANAGER_H_
