
#ifndef GAMESTATSMANAGER_H_
#define GAMESTATSMANAGER_H_

#include "cocos2d.h"
#include <string>

class GameStatsManager : public cocos2d::CCNode {
public:
    static GameStatsManager* create();
    virtual ~GameStatsManager();

    void dataLoaded(DS_Dictionary*);
    void firstSetup();
    void getItemKey(int, int);
    void getLevelKey(GJGameLevel*);
    void getLevelKey(int, bool, bool, bool, bool);
    void hasUserCoin(char const*);
    void sharedState();
    void addStoreItem(int, int, int, int, ShopType);
    void createReward(GJRewardType, int, std::string);
    void encodeDataTo(DS_Dictionary*);
    void getChallenge(int);
    void getRewardKey(GJRewardType, int);
    void getStoreItem(int);
    void getStoreItem(int, int);
    void isSecretCoin(std::string);
    void purchaseItem(int);
    void resetPreSync();
    void collectReward(GJRewardType, GJRewardItem*);
    void getMapPackKey(int);
    void getRewardItem(GJRewardType);
    void hasSecretCoin(char const*);
    void incrementStat(char const*);
    void incrementStat(char const*, int);
    void isItemEnabled(UnlockType, int);
    void storeUserCoin(char const*);
    void tryFixPathBug();
    void awardSecretKey();
    void completedLevel(GJGameLevel*);
    void getCurrencyKey(GJGameLevel*);
    void getStatFromKey(StatKey);
    void isItemUnlocked(UnlockType, int);
    void isPathUnlocked(StatKey);
    void resetUserCoins();
    void storeChallenge(int, GJChallengeItem*);
    void unlockGauntlet(int);
    void claimListReward(GJLevelList*);
    void getBaseCurrency(int, bool, int);
    void getBaseDiamonds(int);
    void getChallengeKey(GJChallengeItem*);
    void getStarLevelKey(GJGameLevel*);
    void removeChallenge(int);
    void restorePostSync();
    void setStatIfHigher(char const*, int);
    void starsForMapPack(int);
    void storeEventChest(int, GJRewardItem*);
    void storeSecretCoin(char const*);
    void uncompleteLevel(GJGameLevel*);
    void unlockGoldChest(int);
    void unlockPathChest(int);
    void verifyUserCoins();
    void accountIDForIcon(int, UnlockType);
    void areRewardsLoaded();
    void checkAchievement(char const*);
    void completedMapPack(GJMapPack*);
    void createStoreItems();
    void getBonusDiamonds(int);
    void getDailyLevelKey(int);
    void getDemonLevelKey(GJGameLevel*);
    void getListRewardKey(GJLevelList*);
    void getPathRewardKey(int);
    void getSecretCoinKey(char const*);
    void preProcessReward(GJRewardItem*);
    void preSaveGameStats();
    void recountUserCoins(bool);
    void setupIconCredits();
    void storeOnlineChest(std::string, GJRewardItem*);
    void storeRewardState(GJRewardType, int, int, std::string);
    void toggleEnableItem(UnlockType, int, bool);
    void updateActivePath(StatKey);
    void canItemBeUnlocked(int, UnlockType);
    void countSecretChests(GJRewardType);
    void getEventRewardKey(int);
    void hasCompletedLevel(GJGameLevel*);
    void isSecretCoinValid(std::string);
    void postLoadGameStats();
    void resetSpecialChest(std::string);
    void shopTypeForItemID(int);
    void unlockOnlineChest(std::string);
    void unlockSecretChest(int);
    void checkCoinsForLevel(GJGameLevel*);
    void collectVideoReward(int);
    void completedChallenge(GJChallengeItem*);
    void completedStarLevel(GJGameLevel*);
    void getItemUnlockState(int, UnlockType);
    void getNextGoldChestID();
    void getQueuedChallenge(int);
    void hasPendingUserCoin(char const*);
    void incrementChallenge(GJChallengeType, int);
    void isGauntletUnlocked(int);
    void setStarsForMapPack(int, int);
    void storeChallengeTime(int);
    void unlockSpecialChest(std::string);
    void areChallengesLoaded();
    void completedDailyLevel(GJGameLevel*);
    void completedDemonLevel(GJGameLevel*);
    void hasCompletedMapPack(int);
    void incrementActivePath(int);
    void isPathChestUnlocked(int);
    void isStoreItemUnlocked(int);
    void processOnlineChests();
    void recountSpecialStats();
    void resetChallengeTimer();
    void trySelectActivePath();
    void unlockGauntletChest(int);
    void awardOldSpecialStats();
    void checkCoinAchievement(GJGameLevel*);
    void getCompletedMapPacks();
    void getGauntletRewardKey(int);
    void getNextVideoAdReward();
    void hasClaimedListReward(GJLevelList*);
    void shouldAwardSecretKey();
    void storePendingUserCoin(char const*);
    void storeQueuedChallenge(int, GJChallengeItem*);
    void usernameForAccountID(int);
    void awardCurrencyForLevel(GJGameLevel*);
    void awardDiamondsForLevel(GJGameLevel*);
    void getSecretChestForItem(int, UnlockType);
    void hasCompletedChallenge(GJChallengeItem*);
    void hasCompletedMainLevel(int);
    void hasCompletedStarLevel(GJGameLevel*);
    void isSecretChestUnlocked(int);
    void keyCostForSecretChest(int);
    void processChallengeQueue(int);
    void removeQueuedChallenge(int);
    void createSecretChestItems();
    void getItemUnlockStateLite(int, UnlockType);
    void hasCompletedDailyLevel(int);
    void hasCompletedDemonLevel(GJGameLevel*);
    void hasRewardBeenCollected(GJRewardType, int);
    void isSpecialChestUnlocked(std::string);
    void verifyPathAchievements();
    void createSpecialChestItems();
    void getBaseCurrencyForLevel(GJGameLevel*);
    void getRewardForSecretChest(int);
    void hasCompletedOnlineLevel(int);
    void isGauntletChestUnlocked(int);
    void linkSpecialChestUnlocks(GJRewardItem*, std::string);
    void registerRewardsFromItem(GJRewardItem*);
    void createSecretChestRewards();
    void getRewardForSpecialChest(std::string);
    void getSecretOnlineRewardKey(int);
    void countUnlockedSecretChests(GJRewardType);
    void getCollectedCoinsForLevel(GJGameLevel*);
    void getSpecialChestKeyForItem(int, UnlockType);
    void getTotalCollectedCurrency();
    void getTotalCollectedDiamonds();
    void hasCompletedGauntletLevel(int);
    void generateItemUnlockableData();
    void getAwardedCurrencyForLevel(GJGameLevel*);
    void getAwardedDiamondsForLevel(GJGameLevel*);
    void addSimpleSpecialChestReward(std::string, UnlockType, int, bool);
    void addSpecialRewardDescription(std::string, std::string);
    void getSecondaryQueuedChallenge(int);
    void getSpecialRewardDescription(std::string, bool);
    void getSpecialUnlockDescription(int, UnlockType, bool);
    void isSpecialChestLiteUnlockable(std::string);
    void removeErrorFromSpecialChests();
    void resetSpecialStatAchievements();
    void storeSecondaryQueuedChallenge(int, GJChallengeItem*);
    void markLevelAsCompletedAndClaimed(GJGameLevel*);
    void removeQueuedSecondaryChallenge(int);
    void init() override;
    void getStat(char const*);
    void setStat(char const*, int);
    void logCoins();
    void tempClear();

protected:
    std::string m_challengeKey;
    std::string m_currencyKey;
    std::string m_dailyLevelKey;
    std::string m_demonLevelKey;
    int m_diamonds;
    std::string m_eventRewardKey;
    std::string m_gauntletRewardKey;
    std::string m_itemKey;
    int m_keys;
    int m_legendScore;
    std::string m_levelKey;
    std::string m_listRewardKey;
    std::string m_mapPackKey;
    int m_moons;
    int m_nextGoldChestID;
    int m_orbs;
    std::string m_pathRewardKey;
    cocos2d::CCDictionary* m_playerStats;
    std::string m_rewardKey;
    std::string m_secretCoinKey;
    int m_secretCoins;
    std::string m_secretOnlineRewardKey;
    std::string m_specialChestKeyForItem;
    std::string m_starLevelKey;
    int m_stars;
    std::string m_statFromKey;
    int m_userCoins;

};

#endif // GAMESTATSMANAGER_H_
