
#ifndef GAMEOBJECT_H_
#define GAMEOBJECT_H_

#include "cocos2d.h"
#include <string>
#include <vector>

class GameObject : public cocos2d::CCSprite {
public:
    static GameObject* create();
    virtual ~GameObject();

    void addToGroup(int);
    void canReverse();
    void copyGroups(GameObject*);
    void createGlow(std::string);
    void firstSetup();
    void getGroupID(int);
    void getRScaleX();
    void getRScaleY();
    void groupColor(cocos2d::_ccColor3B const&, bool);
    void ignoreFade();
    void removeGlow();
    void setOpacity(unsigned char);
    void setRScaleX(float);
    void setRScaleY(float);
    void setVisible(bool);
    void addRotation(float);
    void addRotation(float, float);
    void commonSetup();
    void customSetup();
    void getColorKey(bool, bool);
    void ignoreEnter();
    void makeVisible();
    void resetGroups();
    void resetObject();
    void setPosition(cocos2d::CCPoint const&);
    void setRotation(float);
    void setStartPos(cocos2d::CCPoint);
    void shouldLockX();
    void addEmptyGlow();
    void canBeOrdered();
    void colorForMode(int, bool);
    void getBallFrame(int);
    void getBoxOffset();
    void getGlowFrame(std::string);
    void getMainColor();
    void isFacingDown();
    void isFacingLeft();
    void selectObject(cocos2d::_ccColor3B);
    void setGlowColor(cocos2d::_ccColor3B const&);
    void setRRotation(float);
    void setRotationX(float);
    void setRotationY(float);
    void addNewSlope01(bool);
    void addNewSlope02(bool);
    void canRotateFree();
    void claimParticle();
    void createWithKey(int);
    void destroyObject();
    void disableObject();
    void getColorFrame(std::string);
    void getColorIndex();
    void getObjectRect(float, float);
    void getObjectRect();
    void getParentMode();
    void getSaveString(GJBaseGameLayer*);
    void getSlopeAngle();
    void isColorObject();
    void isSpeedObject();
    void makeInvisible();
    void restoreObject();
    void setChildColor(cocos2d::_ccColor3B const&);
    void slopeFloorTop();
    void slopeWallLeft();
    void triggerObject(GJBaseGameLayer*, int, std::vector<int> const*);
    void activateObject();
    void addColorSprite(std::string);
    void addCustomChild(std::string, cocos2d::CCPoint, int);
    void assignUniqueID();
    void belongsToGroup(int);
    void deselectObject();
    void getGroupString();
    void getObjectLabel();
    void getObjectRect2(float, float);
    void getOrientedBox();
    void getTextKerning();
    void isBasicTrigger();
    void isColorTrigger();
    void setAreaOpacity(float, float, int);
    void setGlowOpacity(unsigned char);
    void setObjectColor(cocos2d::_ccColor3B const&);
    void setObjectLabel(cocos2d::CCLabelBMFont*);
    void spawnXPosition();
    void updateHSVState();
    void updateStartPos();
    void addToColorGroup(int);
    void addToTempOffset(double, double);
    void createWithFrame(char const*);
    void didScaleXChange();
    void didScaleYChange();
    void duplicateValues(GameObject*);
    void getBoundingRect();
    void getCustomZLayer();
    void getLastPosition();
    void getObjectRadius();
    void getObjectZLayer();
    void getObjectZOrder();
    void getRealPosition();
    void groupOpacityMod();
    void groupWasEnabled();
    void initWithTexture(cocos2d::CCTexture2D*);
    void isSpecialObject();
    void parentForZLayer(int, bool, int);
    void playShineEffect();
    void removeFromGroup(int);
    void resetMoveOffset();
    void setCustomZLayer(int);
    void setLastPosition(cocos2d::CCPoint const&);
    void setupPixelScale();
    void setupSpriteSize();
    void unclaimParticle();
    void updateBlendMode();
    void updateMainColor(cocos2d::_ccColor3B const&);
    void updateMainColor();
    void addInternalChild(cocos2d::CCSprite*, std::string, cocos2d::CCPoint, int);
    void blendModeChanged();
    void canMultiActivate(bool);
    void deactivateObject(bool);
    void dirtifyObjectPos();
    void fastRotateObject(float);
    void getGroupDisabled();
    void getMainColorMode();
    void getScalePosDelta();
    void groupWasDisabled();
    void hasBeenActivated();
    void isSettingsObject();
    void objectFromVector(std::vector<std::string>&, std::vector<void*>&, GJBaseGameLayer*, bool);
    void perspectiveFrame(char const*, int);
    void resetColorGroups();
    void saveActiveColors();
    void setMainColorMode(int);
    void setupColorSprite(int, bool);
    void shouldBlendColor(GJSpriteColor*, bool);
    void triggerActivated(float);
    void updateIsOriented();
    void activatedByPlayer(PlayerObject*);
    void addNewSlope01Glow(bool);
    void addNewSlope02Glow(bool);
    void addToCustomScaleX(float);
    void addToCustomScaleY(float);
    void addToOpacityGroup(int);
    void createSpriteColor(int);
    void customObjectSetup(std::vector<std::string>&, std::vector<void*>&);
    void dirtifyObjectRect();
    void getObjectRotation();
    void getSecondaryColor();
    void hasSecondaryColor();
    void opacityModForMode(int, bool);
    void removeColorSprite();
    void resetRScaleForced();
    void updateMainOpacity();
    void updateOrientedBox();
    void updateStartValues();
    void updateTextKerning(int);
    void animationTriggered();
    void canChangeMainColor();
    void duplicateColorMode(GameObject*);
    void editorColorForMode(int);
    void getHasRotateAction();
    void getObjectDirection();
    void getOuterObjectRect();
    void isBasicEnterEffect(int);
    void isSpawnableTrigger();
    void isStoppableTrigger();
    void reorderColorSprite();
    void resetGroupDisabled();
    void resetMainColorMode();
    void setObjectRectDirty(bool);
    void setupCustomSprites(std::string);
    void transferObjectRect(cocos2d::CCRect&);
    void updateCustomScaleX(float);
    void updateCustomScaleY(float);
    void addCustomBlackChild(std::string, float, bool);
    void addCustomColorChild(std::string);
    void duplicateAttributes(GameObject*);
    void playPickupAnimation(cocos2d::CCSprite*, float, float, float, float);
    void playPickupAnimation(cocos2d::CCSprite*, float, float, float, float, float, float, float, float, bool, float, float);
    void quickUpdatePosition();
    void updateMainColorOnly();
    void updateParticleColor(cocos2d::_ccColor3B const&);
    void usesFreezeAnimation();
    void addColorSpriteToSelf();
    void addInternalGlowChild(std::string, cocos2d::CCPoint);
    void calculateOrientedBox();
    void canChangeCustomColor();
    void createAndAddParticle(int, char const*, int, cocos2d::tCCPositionType);
    void createGroupContainer(int);
    void getObjectRectPointer();
    void getObjectTextureRect();
    void ignoreEditorDuration();
    void isConfigurablePortal();
    void isSpecialSpawnObject();
    void loadGroupsFromString(std::string);
    void particleWasActivated();
    void quickUpdatePosition2();
    void setOrientedRectDirty(bool);
    void updateSecondaryColor(cocos2d::_ccColor3B const&);
    void updateSecondaryColor();
    void usesSpecialAnimation();
    void addMainSpriteToParent(bool);
    void canAllowMultiActivate();
    void dontCountTowardsLimit();
    void getActiveColorForMode(int, bool);
    void getHasSyncedAnimation();
    void getSecondaryColorMode();
    void getUnmodifiedPosition();
    void perspectiveColorFrame(char const*, int);
    void playDestroyObjectAnim(GJBaseGameLayer*);
    void setSecondaryColorMode(int);
    void updateCustomColorType(short);
    void updateParticleOpacity(unsigned char);
    void addColorSpriteToParent(bool);
    void commonInteractiveSetup();
    void getRelativeSpriteColor(int);
    void shouldDrawEditorHitbox();
    void updateSecondaryOpacity();
    void canChangeSecondaryColor();
    void determineSlopeDirection();
    void resetSecondaryColorMode();
    void setDefaultMainColorMode(int);
    void shouldNotHideAnimFreeze();
    void shouldShowPickupEffects();
    void updateObjectEditorColor();
    void editorColorForCustomMode(int);
    void hasBeenActivatedByPlayer(PlayerObject*);
    void isEditorSpawnableTrigger();
    void updateSecondaryColorOnly();
    void createColorGroupContainer(int);
    void updateMainParticleOpacity(unsigned char);
    void updateUnmodifiedPositions();
    void spawnDefaultPickupParticle(GJBaseGameLayer*);
    void addInternalCustomColorChild(std::string, cocos2d::CCPoint, int);
    void createOpacityGroupContainer(int);
    void setDefaultSecondaryColorMode(int);
    void updateSecondaryParticleOpacity(unsigned char);
    void init(char const*) override;
    void update(float) override;
    void addGlow(std::string);
    void isFlipX();
    void isFlipY();
    void setType(GameObjectType);
    void resetMID();
    void setFlipX(bool);
    void setFlipY(bool);
    void setScale(float);
    void isTrigger();
    void setRScale(float);
    void setScaleX(float);
    void setScaleY(float);
    void slopeYPos(cocos2d::CCRect);
    void slopeYPos(GameObject*);
    void slopeYPos(float);
    void getStartPos()) const;
    void getObjectRectDirty()) const;
    void getOrientedRectDirty()) const;
    void getType()) const;

protected:
    bool m_activeColorForMode;
    int m_baseColorID;
    cocos2d::_ccColor3B m_childColor;
    cocos2d::_ccColor3B m_colorFrame;
    int m_colorIndex;
    cocos2d::_ccColor3B m_colorKey;
    cocos2d::_ccColor3B m_defaultMainColorMode;
    cocos2d::_ccColor3B m_defaultSecondaryColorMode;
    int m_detailColorID;
    cocos2d::_ccColor3B m_glowColor;
    int m_groupID;
    std::string m_groupString;
    bool m_hasBeenActivated;
    bool m_isActive;
    cocos2d::CCPoint m_lastPosition;
    cocos2d::_ccColor3B m_mainColor;
    cocos2d::_ccColor3B m_mainColorMode;
    cocos2d::_ccColor3B m_objectColor;
    int m_objectID;
    cocos2d::CCPoint m_objectRectPointer;
    cocos2d::CCPoint m_position;
    float m_rScale;
    float m_rScaleX;
    float m_rScaleY;
    cocos2d::CCPoint m_realPosition;
    cocos2d::_ccColor3B m_relativeSpriteColor;
    float m_rotation;
    std::string m_saveString;
    float m_scale;
    float m_scalePosDelta;
    float m_scaleX;
    float m_scaleY;
    cocos2d::_ccColor3B m_secondaryColor;
    cocos2d::_ccColor3B m_secondaryColorMode;
    int m_section;
    cocos2d::CCPoint m_unmodifiedPosition;
    bool m_visible;
    float m_x;
    float m_y;
    int m_zOrder;

};

#endif // GAMEOBJECT_H_
