
#ifndef GAMESTATSMANAGER_H_
#define GAMESTATSMANAGER_H_

#include "cocos2d.h"
#include <string>

class GameStatsManager : public cocos2d::CCNode {
public:
    static GameStatsManager* create();
    virtual ~GameStatsManager();

    void dataLoaded(DS_Dictionary*);
    void firstSetup();
    std::string getItemKey(int, int);
    std::string getLevelKey(GJGameLevel*);
    std::string getLevelKey(int, bool, bool, bool, bool);
    bool hasUserCoin(char const*);
    GameStatsManager* sharedState();
    void addStoreItem(int, int, int, int, ShopType);
    void createReward(GJRewardType, int, std::string);
    void encodeDataTo(DS_Dictionary*);
    void getChallenge(int);
    std::string getRewardKey(GJRewardType, int);
    void getStoreItem(int);
    void getStoreItem(int, int);
    bool isSecretCoin(std::string);
    void purchaseItem(int);
    void resetPreSync();
    void collectReward(GJRewardType, GJRewardItem*);
    std::string getMapPackKey(int);
    void getRewardItem(GJRewardType);
    bool hasSecretCoin(char const*);
    void incrementStat(char const*);
    void incrementStat(char const*, int);
    bool isItemEnabled(UnlockType, int);
    void storeUserCoin(char const*);
    void tryFixPathBug();
    void awardSecretKey();
    void completedLevel(GJGameLevel*);
    std::string getCurrencyKey(GJGameLevel*);
    std::string getStatFromKey(StatKey);
    bool isItemUnlocked(UnlockType, int);
    bool isPathUnlocked(StatKey);
    void resetUserCoins();
    void storeChallenge(int, GJChallengeItem*);
    void unlockGauntlet(int);
    void claimListReward(GJLevelList*);
    void getBaseCurrency(int, bool, int);
    void getBaseDiamonds(int);
    std::string getChallengeKey(GJChallengeItem*);
    std::string getStarLevelKey(GJGameLevel*);
    void removeChallenge(int);
    void restorePostSync();
    void setStatIfHigher(char const*, int);
    void starsForMapPack(int);
    void storeEventChest(int, GJRewardItem*);
    void storeSecretCoin(char const*);
    void uncompleteLevel(GJGameLevel*);
    void unlockGoldChest(int);
    void unlockPathChest(int);
    void verifyUserCoins();
    void accountIDForIcon(int, UnlockType);
    bool areRewardsLoaded();
    void checkAchievement(char const*);
    void completedMapPack(GJMapPack*);
    void createStoreItems();
    void getBonusDiamonds(int);
    std::string getDailyLevelKey(int);
    std::string getDemonLevelKey(GJGameLevel*);
    std::string getListRewardKey(GJLevelList*);
    std::string getPathRewardKey(int);
    std::string getSecretCoinKey(char const*);
    void preProcessReward(GJRewardItem*);
    void preSaveGameStats();
    void recountUserCoins(bool);
    void setupIconCredits();
    void storeOnlineChest(std::string, GJRewardItem*);
    void storeRewardState(GJRewardType, int, int, std::string);
    void toggleEnableItem(UnlockType, int, bool);
    void updateActivePath(StatKey);
    bool canItemBeUnlocked(int, UnlockType);
    int countSecretChests(GJRewardType);
    std::string getEventRewardKey(int);
    bool hasCompletedLevel(GJGameLevel*);
    bool isSecretCoinValid(std::string);
    void postLoadGameStats();
    void resetSpecialChest(std::string);
    void shopTypeForItemID(int);
    void unlockOnlineChest(std::string);
    void unlockSecretChest(int);
    void checkCoinsForLevel(GJGameLevel*);
    void collectVideoReward(int);
    void completedChallenge(GJChallengeItem*);
    void completedStarLevel(GJGameLevel*);
    void getItemUnlockState(int, UnlockType);
    void getNextGoldChestID();
    void getQueuedChallenge(int);
    bool hasPendingUserCoin(char const*);
    void incrementChallenge(GJChallengeType, int);
    bool isGauntletUnlocked(int);
    void setStarsForMapPack(int, int);
    void storeChallengeTime(int);
    void unlockSpecialChest(std::string);
    bool areChallengesLoaded();
    void completedDailyLevel(GJGameLevel*);
    void completedDemonLevel(GJGameLevel*);
    bool hasCompletedMapPack(int);
    void incrementActivePath(int);
    bool isPathChestUnlocked(int);
    bool isStoreItemUnlocked(int);
    void processOnlineChests();
    void recountSpecialStats();
    void resetChallengeTimer();
    void trySelectActivePath();
    void unlockGauntletChest(int);
    void awardOldSpecialStats();
    void checkCoinAchievement(GJGameLevel*);
    void getCompletedMapPacks();
    std::string getGauntletRewardKey(int);
    void getNextVideoAdReward();
    bool hasClaimedListReward(GJLevelList*);
    bool shouldAwardSecretKey();
    void storePendingUserCoin(char const*);
    void storeQueuedChallenge(int, GJChallengeItem*);
    void usernameForAccountID(int);
    void awardCurrencyForLevel(GJGameLevel*);
    void awardDiamondsForLevel(GJGameLevel*);
    void getSecretChestForItem(int, UnlockType);
    bool hasCompletedChallenge(GJChallengeItem*);
    bool hasCompletedMainLevel(int);
    bool hasCompletedStarLevel(GJGameLevel*);
    bool isSecretChestUnlocked(int);
    void keyCostForSecretChest(int);
    void processChallengeQueue(int);
    void removeQueuedChallenge(int);
    GameStatsManager* createSecretChestItems();
    void getItemUnlockStateLite(int, UnlockType);
    bool hasCompletedDailyLevel(int);
    bool hasCompletedDemonLevel(GJGameLevel*);
    bool hasRewardBeenCollected(GJRewardType, int);
    bool isSpecialChestUnlocked(std::string);
    void verifyPathAchievements();
    GameStatsManager* createSpecialChestItems();
    void getBaseCurrencyForLevel(GJGameLevel*);
    void getRewardForSecretChest(int);
    bool hasCompletedOnlineLevel(int);
    bool isGauntletChestUnlocked(int);
    void linkSpecialChestUnlocks(GJRewardItem*, std::string);
    void registerRewardsFromItem(GJRewardItem*);
    GameStatsManager* createSecretChestRewards();
    void getRewardForSpecialChest(std::string);
    std::string getSecretOnlineRewardKey(int);
    int countUnlockedSecretChests(GJRewardType);
    void getCollectedCoinsForLevel(GJGameLevel*);
    std::string getSpecialChestKeyForItem(int, UnlockType);
    void getTotalCollectedCurrency();
    void getTotalCollectedDiamonds();
    bool hasCompletedGauntletLevel(int);
    void generateItemUnlockableData();
    void getAwardedCurrencyForLevel(GJGameLevel*);
    void getAwardedDiamondsForLevel(GJGameLevel*);
    void addSimpleSpecialChestReward(std::string, UnlockType, int, bool);
    void addSpecialRewardDescription(std::string, std::string);
    void getSecondaryQueuedChallenge(int);
    void getSpecialRewardDescription(std::string, bool);
    void getSpecialUnlockDescription(int, UnlockType, bool);
    bool isSpecialChestLiteUnlockable(std::string);
    void removeErrorFromSpecialChests();
    void resetSpecialStatAchievements();
    void storeSecondaryQueuedChallenge(int, GJChallengeItem*);
    void markLevelAsCompletedAndClaimed(GJGameLevel*);
    void removeQueuedSecondaryChallenge(int);
    bool init() override;
    void getStat(char const*);
    void setStat(char const*, int);
    void logCoins();
    void tempClear();

protected:
    std::string m_challengeKey;
    std::string m_currencyKey;
    std::string m_dailyLevelKey;
    std::string m_demonLevelKey;
    int m_diamonds;
    std::string m_eventRewardKey;
    std::string m_gauntletRewardKey;
    std::string m_itemKey;
    int m_keys;
    int m_legendScore;
    std::string m_levelKey;
    std::string m_listRewardKey;
    std::string m_mapPackKey;
    int m_moons;
    int m_nextGoldChestID;
    int m_orbs;
    std::string m_pathRewardKey;
    cocos2d::CCDictionary* m_playerStats;
    std::string m_rewardKey;
    std::string m_secretCoinKey;
    int m_secretCoins;
    std::string m_secretOnlineRewardKey;
    std::string m_specialChestKeyForItem;
    std::string m_starLevelKey;
    int m_stars;
    std::string m_statFromKey;
    int m_userCoins;

};

#endif // GAMESTATSMANAGER_H_
