// ============================================================
// GJBaseGameLayer.h — Reconstructed from libcocos2dcpp.so
// Part of Geometry Dash v2.2.144 decompilation project
// ============================================================

#ifndef GJBASEGAMELAYER_H_
#define GJBASEGAMELAYER_H_

#include "GJEffectManager.h"
#include "PlayerObject.h"
#include "cocos2d.h"
#include <string>
#include <unordered_map>
#include <vector>

// Forward declarations
class GJEffectManager;
class PlayerObject;

class GJBaseGameLayer : public cocos2d::CCLayer {
public:
    static GJBaseGameLayer* create();
    virtual ~GJBaseGameLayer();
    virtual ~GJBaseGameLayer();
    virtual ~GJBaseGameLayer();

    void addToGroup(GameObject*, int, bool);
    void applyRemap(EffectGameObject*, std::vector<int> const&, std::unordered_map<int, int>, std::equal_to<int>, std::allocator<std::pair<const int, int> > >&);
    void applyShake(cocos2d::CCPoint&);
    void atlasValue(int);
    void bumpPlayer(PlayerObject*, EffectGameObject*);
    void getBumpMod(PlayerObject*, int);
    void isFlipping();
    void moveObject(GameObject*, double, double, bool);
    void pauseAudio();
    void pickupItem(EffectGameObject*);
    void postUpdate(float);
    void resetAudio();
    void resetLevel();
    void sortGroups();
    void spawnGroup(int, bool, double, std::vector<int> const&, int, int);
    void swapGround(int);
    void updateOBB2(cocos2d::CCRect);
    void updateZoom(float, float, int, float, int, int);
    void addGuideArt(GameObject*);
    void addKeyframe(KeyframeGameObject*);
    void addToGroups(GameObject*, bool);
    void addUIObject(GameObject*);
    void cameraMoveX(float, float, float, bool);
    void cameraMoveY(float, float, float, bool);
    void checkForEnd();
    void flipGravity(PlayerObject*, bool, bool);
    void flipObjects();
    void moveObjects(cocos2d::CCArray*, double, double, bool);
    void queueButton(int, bool, bool, double);
    void resetCamera();
    void resetPlayer();
    void resetRecord(int, bool);
    void resumeAudio();
    void setupLayers();
    void setupReplay(std::string);
    void shakeCamera(float, float, float);
    void spawnObject(GameObject*, double, std::vector<int> const&);
    void toggleGroup(int, bool);
    void updateColor(cocos2d::_ccColor3B&, float, int, bool, float, cocos2d::_ccHSVValue&, int, bool, EffectGameObject*, int, int);
    void addToSection(GameObject*);
    void asyncGLoaded(int);
    void createPlayer();
    void flipFinished();
    void getItemValue(int, int);
    void handleButton(bool, int, bool);
    void processItems();
    void recordAction(int, bool, bool);
    void restoreRemap(EffectGameObject*, std::unordered_map<int, int>, std::equal_to<int>, std::allocator<std::pair<const int, int> > >&);
    void rotateObject(GameObject*, float);
    void spawnPlayer2();
    void tryGetObject(int);
    void updateCamera(float);
    void updateReplay();
    void addAreaEffect(EnterEffectObject*, std::vector<EnterEffectInstance>*, GJAreaActionType);
    void applyTimeWarp(float);
    void asyncBGLoaded(int);
    void asyncMGLoaded(int);
    void canProcessSFX(SFXTriggerState&, std::unordered_map<int, int>, std::equal_to<int>, std::allocator<std::pair<const int, int> > >&, std::unordered_map<int, float>, std::equal_to<int>, std::allocator<std::pair<const int, float> > >&, std::vector<SFXTriggerState>&);
    void checkSnapshot();
    void claimParticle(std::string, int);
    void destroyObject(GameObject*);
    void destroyPlayer(PlayerObject*, GameObject*);
    void enterDualMode(GameObject*, bool);
    void getMaxPortalY();
    void getMinPortalY();
    void getSpecialKey(int, bool, bool);
    void hasUniqueCoin(EffectGameObject*);
    void preResumeGame();
    void queueTimeWarp(float);
    void removePlayer2();
    void rotateObjects(cocos2d::CCArray*, float, cocos2d::CCPoint, cocos2d::CCPoint, bool, bool);
    void spawnParticle(char const*, int, cocos2d::tCCPositionType, cocos2d::CCPoint);
    void toggleFlipped(bool, bool);
    void toggleGlitter(bool);
    void updateTimeMod(float, bool, bool);
    void animatePortalY(float, float, float, float);
    void canTouchObject(GameObject*);
    void checkCollision(int, int);
    void createParticle(int, char const*, int, cocos2d::tCCPositionType);
    void getGroupParent(int);
    void getMinDistance(cocos2d::CCPoint, cocos2d::CCArray*, float, int);
    void getOtherPlayer(PlayerObject*);
    void getParticleKey(int, char const*, int, cocos2d::tCCPositionType);
    void getRecordExtra();
    void getStaticGroup(int);
    void getStickyGroup(int);
    void getTargetGroup(int, int);
    void gravBumpPlayer(PlayerObject*, EffectGameObject*);
    void lightningFlash(cocos2d::CCPoint, cocos2d::_ccColor3B);
    void lightningFlash(cocos2d::CCPoint, cocos2d::CCPoint, cocos2d::_ccColor3B, float, float, int, bool, float);
    void removeKeyframe(KeyframeGameObject*);
    void reparentObject(cocos2d::CCNode*, cocos2d::CCNode*);
    void rotateGameplay(RotateGameplayGameObject*);
    void setGroupParent(GameObject*, int);
    void sortAllGroupsX();
    void stopSFXTrigger(SFXTriggerGameObject*);
    void swapBackground(int);
    void syncBGTextures();
    void teleportPlayer(TeleportPortalObject*, PlayerObject*);
    void toggleDualMode(GameObject*, bool, PlayerObject*, bool);
    void tryResumeAudio();
    void updateCounters(int, int);
    void updateGuideArt();
    void updateTimeWarp(float);
    void addRemapTargets(std::set<int, std::less<int>, std::allocator<int> >&);
    void checkCollisions(PlayerObject*, float, bool);
    void checkSpawnAbuse();
    void claimMoveAction(int, bool);
    void collectedObject(EffectGameObject*);
    void getGroundHeight(PlayerObject*, int);
    void getParticleKey2(std::string);
    void getPortalTarget(TeleportPortalObject*);
    void getRecordString(bool);
    void isButtonAllowed(bool, int, bool);
    void isPlayer2Button(int);
    void moveCameraToPos(cocos2d::CCPoint);
    void objectsCollided(int, int);
    void parentForZLayer(int, bool, int, int);
    void playFlashEffect(float, int, float);
    void processCommands(float, bool, bool);
    void processSFXState(SFXTriggerState*, SFXTriggerState*, int, float);
    void removeFromGroup(GameObject*, int);
    void resetRecordFull();
    void setupLevelStart(LevelSettingsObject*);
    void stopCameraShake();
    void switchToFlyMode(PlayerObject*, GameObject*, bool, int);
    void toggleInfoLabel();
    void unclaimParticle(char const*, cocos2d::CCParticleSystemQuad*);
    void unlinkAllEvents();
    void updateDebugDraw();
    void updateMGOffsetY(float, float, int, float, int, int);
    void updateParticles(float);
    void updateTimeLabel(int, int, bool);
    void addObjectCounter(LabelGameObject*);
    void addPickupTrigger(CountTriggerGameObject*);
    void buttonIDToButton(int);
    void buttonIsRelevant(PlayerButtonCommand const&);
    void controlEventLink(int, int, GJActionCommand);
    void createBackground(int);
    void createTextLayers();
    void exitStaticCamera(bool, bool, float, int, float, bool, float, bool);
    void getModifiedDelta(float);
    void getSavedPosition(int, float);
    void loadUpToPosition(float, int, int);
    void opacityForObject(GameObject*);
    void playerTookDamage(PlayerObject*);
    void processSongState(int, float, float, int, float, float, std::vector<SongTriggerState>*, SongTriggerGameObject*);
    void removeBackground();
    void removeFromGroups(GameObject*);
    void reverseDirection(EffectGameObject*);
    void sortStickyGroups();
    void swapMiddleground(int);
    void switchToRollMode(PlayerObject*, GameObject*, bool);
    void toggleLockPlayer(bool, bool);
    void tryGetMainObject(int);
    void updateBGArtSpeed(float, float);
    void updateCameraEdge(int, int);
    void updateCameraMode(EffectGameObject*, bool);
    void updateDualGround(PlayerObject*, int, bool, float);
    void updateMGArtSpeed(float, float);
    void updateVisibility(float);
    void addToGroupParents(GameObject*);
    void addToSpeedObjects(EffectGameObject*);
    void checkRepellPlayer();
    void checkSpawnObjects();
    void controlAreaEffect(EnterEffectObject*, std::vector<EnterEffectInstance>*, GJActionCommand);
    void createGroundLayer(int, int);
    void didRotateGameplay();
    void gameEventToString(GJGameEvent);
    void getCapacityString();
    void getEnterEasingKey(int, float);
    void getFollowSpeedVal(GameObject*, int, int, float, float);
    void getOptimizedGroup(int);
    void getPlayTimerMilli();
    void getPlayerButtonID(int, bool);
    void loadLevelSettings();
    void moveObjectsSilent(int, double, double);
    void orderSpawnObjects();
    void playGravityEffect(bool);
    void playSpeedParticle(float);
    void playerTouchedRing(PlayerObject*, RingObject*);
    void positionUIObjects();
    void processSFXObjects();
    void removeGroundLayer();
    void removeGroupParent(int);
    void resetStaticCamera(bool, bool);
    void rotateAreaObjects(GameObject*, cocos2d::CCArray*, float, bool);
    void setStartPosObject(StartPosObject*);
    void sortSectionVector();
    void switchToRobotMode(PlayerObject*, GameObject*, bool);
    void toggleProgressbar();
    void triggerAreaEffect(EnterEffectObject*);
    void tryGetGroupParent(int);
    void updateAttemptTime(float);
    void updateCameraBGArt(cocos2d::CCPoint, float);
    void updateLevelColors();
    void updateShaderLayer(float);
    void updateTimerLabels();
    void activateCustomRing(RingObject*);
    void activateEndTrigger(int, bool, bool);
    void activateSFXTrigger(SFXTriggerGameObject*);
    void animateInGroundNew(bool, float, bool);
    void applyLevelSettings(GameObject*);
    void clearPickedUpItems();
    void createMiddleground(int);
    void gameEventTriggered(GJGameEvent, int, int);
    void generateSpawnRemap();
    void getCameraEdgeValue(int);
    void getMoveTargetDelta(EffectGameObject*, bool);
    void getPortalTargetPos(TeleportPortalObject*, GameObject*, PlayerObject*);
    void groupStickyObjects(cocos2d::CCArray*);
    void loadStartPosObject();
    void modifyGroupPhysics(AdvancedFollowEditObject*, cocos2d::CCArray*);
    void optimizeMoveGroups();
    void playExitDualEffect(PlayerObject*);
    void processAreaActions(float, bool);
    void processAreaEffects(std::vector<EnterEffectInstance>*, GJAreaActionType, float, bool);
    void processCheckpoints();
    void processMoveActions();
    void reAddToStickyGroup(GameObject*);
    void registerSpawnRemap(std::vector<ChanceObject>&);
    void removeMiddleground();
    void resetGroupCounters(bool);
    void switchToSpiderMode(PlayerObject*, GameObject*, bool);
    void toggleHideAttempts(bool);
    void toggleMGVisibility(bool);
    void triggerMoveCommand(EffectGameObject*);
    void updateEnterEffects(float);
    void updateMaxGameplayY();
    void updateQueuedLabels();
    void updateVerifyDamage();
    void activateSongTrigger(SongTriggerGameObject*);
    void animateOutGroundNew(bool);
    void applySFXEditTrigger(int, int, SFXTriggerGameObject*);
    void checkpointActivated(CheckpointGameObject*);
    void claimCustomParticle(std::string const&, cocos2d::ParticleStruct const&, int, int, int, bool);
    void claimRotationAction(int, int, float&, float&, bool, bool);
    void getEnterEasingValue(float, int, float, int);
    void getTargetFlyCameraY(GameObject*);
    void maxZOrderForShaderZ(int);
    void minZOrderForShaderZ(int);
    void modifyObjectPhysics(AdvancedFollowEditObject*, GameObjectPhysics&);
    void performMathRounding(double, int);
    void playerTouchedObject(PlayerObject*, GameObject*);
    void preUpdateVisibility(float);
    void processCameraObject(GameObject*, PlayerObject*);
    void processStateObjects();
    void registerStateObject(EffectGameObject*);
    void resetGradientLayers();
    void resetLevelVariables();
    void restoreAllUIObjects();
    void spawnGroupTriggered(int, float, bool, std::vector<int> const&, int, int);
    void spawnObjectsInOrder(cocos2d::CCArray*, double, std::vector<int> const&, int, int);
    void staticObjectsInRect(cocos2d::CCRect, bool);
    void updateCameraOffsetX(float, float, int, float, int, int);
    void updateCameraOffsetY(float, float, int, float, int, int);
    void updateGroundShadows();
    void updateKeyframeOrder(int);
    void updateLayerCapacity(std::string);
    void updateObjectSection(GameObject*);
    void updateSpecialLabels();
    void visitWithColorFlash();
    void activateEventTrigger(EventLinkTrigger*, std::vector<int> const&);
    void activateResetTrigger(EffectGameObject*);
    void activateTimerTrigger(TimerTriggerGameObject*, std::vector<int> const&);
    void addCustomEnterEffect(EnterEffectObject*, bool);
    void calculateColorGroups();
    void checkCollisionBlocks(EffectGameObject*, std::vector<EffectGameObject*>*, int);
    void createCustomParticle(std::string const&, cocos2d::ParticleStruct const&, int, bool);
    void generateTargetGroups();
    void getCenterGroupObject(int, int);
    void getSingleGroupObject(int);
    void getTargetGroupOrigin(int, int);
    void performMathOperation(double, double, int);
    void playAnimationCommand(int, int);
    void playerTouchedTrigger(PlayerObject*, EffectGameObject*);
    void playerWillSwitchMode(PlayerObject*, GameObject*);
    void processFollowActions();
    void processQueuedButtons(float, bool);
    void rectIntersectsCircle(cocos2d::CCRect, cocos2d::CCPoint, float);
    void refreshCounterLabels();
    void refreshKeyframeAnims();
    void removeAllCheckpoints();
    void reorderObjectSection(GameObject*);
    void spawnParticleTrigger(SpawnParticleGameObject*);
    void spawnParticleTrigger(int, cocos2d::CCPoint, float, float);
    void speedForShaderTarget(int);
    void stopAllGroundActions();
    void toggleGroupTriggered(int, bool, std::vector<int> const&, int, int);
    void transformAreaObjects(GameObject*, cocos2d::CCArray*, float, float, bool);
    void triggerGravityChange(EffectGameObject*, int);
    void triggerRotateCommand(EnhancedTriggerObject*);
    void triggerShaderCommand(ShaderGameObject*);
    void ungroupStickyObjects(cocos2d::CCArray*);
    void updateGradientLayers();
    void updatePlatformerTime();
    void updateScreenRotation(float, bool, bool, float, int, float, int, int);
    void activatedAudioTrigger(SFXTriggerGameObject*);
    void activatedAudioTrigger(SFXTriggerGameObject*, float);
    void assignNewStickyGroups(cocos2d::CCArray*);
    void collisionCheckObjects(PlayerObject*, std::vector<GameObject*>*, int, float);
    void controlDynamicCommand(EffectGameObject*, int, std::vector<DynamicObjectAction>&, GJActionCommand);
    void createNewKeyframeAnim();
    void damagingObjectsInRect(cocos2d::CCRect, bool);
    void getCustomEnterEffects(int, bool);
    void getGroupParentsString(GameObject*);
    void getScaledGroundHeight(float);
    void objectTypeToGameEvent(int);
    void playKeyframeAnimation(KeyframeAnimTriggerObject*, std::vector<int> const&);
    void playerCircleCollision(PlayerObject*, GameObject*);
    void processOptionsTrigger(GameOptionsTrigger*);
    void removeFromStickyGroup(GameObject*);
    void removeReleasedButtons();
    void shouldExitHackedLevel();
    void stopCustomEnterEffect(EnterEffectObject*);
    void stopCustomEnterEffect(EnterEffectObject*, bool);
    void toggleAudioVisualizer(bool);
    void toggleMusicInPractice();
    void unclaimCustomParticle(std::string const&, cocos2d::CCParticleSystemQuad*);
    void updateAudioVisualizer();
    void updateCollisionBlocks();
    void updateExtraGameLayers();
    void updateGameplayOffsetX(int, bool);
    void updateGameplayOffsetY(int, bool);
    void updateStaticCameraPos(cocos2d::CCPoint, bool, bool, bool, float, int, float);
    void activateSFXEditTrigger(SFXTriggerGameObject*);
    void animateInDualGroundNew(GameObject*, float, bool, float);
    void canBeActivatedByPlayer(PlayerObject*, EffectGameObject*);
    void controlGradientTrigger(GradientTriggerObject*, GJActionCommand);
    void controlTriggersInGroup(int, GJActionCommand);
    void getGroundHeightForMode(int);
    void objectIntersectsCircle(GameObject*, GameObject*);
    void playerIntersectsCircle(PlayerObject*, GameObject*);
    void prepareTransformParent(bool);
    void processMoveActionsStep(float, bool);
    void processRotationActions();
    void removeFromGroupParents(GameObject*);
    void resetSongTriggerValues();
    void resetSpawnChannelIndex();
    void toggleGroundVisibility(bool);
    void togglePlayerVisibility(bool);
    void togglePlayerVisibility(bool, bool);
    void triggerGradientCommand(GradientTriggerObject*);
    void updateAllObjectSection();
    void updateSpecialGroupData();
    void activateItemEditTrigger(ItemTriggerGameObject*);
    void activateSongEditTrigger(SongTriggerGameObject*);
    void controlAreaEffectWithID(int, int, GJActionCommand);
    void countCollectedUserCoins();
    void getPlayTimerFullSeconds();
    void getRotateCommandTargets(EnhancedTriggerObject*, GameObject*&, GameObject*&, GameObject*&);
    void moveObjectToStaticGroup(GameObject*);
    void playerWasTouchingObject(PlayerObject*, GameObject*);
    void positionForShaderTarget(int);
    void processReplayCheckpoint(int);
    void processTransformActions(bool);
    void removeObjectFromSection(GameObject*);
    void resetActiveEnterEffects();
    void resetMoveOptimizedValue();
    void resetStoppedAreaObjects();
    void testInstantCountTrigger(int, int, int, bool, int, std::vector<int> const&, int, int);
    void togglePlayerStreakBlend(bool, bool);
    void triggerTransformCommand(TransformTriggerGameObject*);
    void updateActiveEnterEffect(EnterEffectObject*);
    void updateExtendedCollision(GameObject*, bool);
    void addProximityVolumeEffect(int, int, SFXTriggerGameObject*);
    void generateVisibilityGroups();
    void manualUpdateObjectColors(GameObject*);
    void processAreaVisualActions(float);
    void removeCustomEnterEffects(int, bool);
    void removeTemporaryParticles();
    void updateInternalCamOffsetX(float, float, float);
    void updateInternalCamOffsetY(float, float, float);
    void volumeForProximityEffect(SFXTriggerInstance&);
    void controlDynamicMoveCommand(EffectGameObject*, int, GJActionCommand);
    void convertToClosestDirection(float, float);
    void generateEnterEasingBuffer(int, float);
    void generatePickupAnimRandVal(GameObject*, float&, float&);
    void increaseBatchNodeCapacity();
    void shouldUseSubstepForButton(float);
    void triggerDynamicMoveCommand(EffectGameObject*);
    void updateLegacyLayerCapacity(int, int, int, int);
    void updateSavePositionObjects();
    void activateItemCompareTrigger(ItemTriggerGameObject*, std::vector<int> const&);
    void createPlayerCollisionBlock();
    void generateEnterEasingBuffers(EnterEffectObject*);
    void getActiveOrderSpawnObjects();
    void loadGroupParentsFromString(GameObject*, std::string);
    void prepareSavePositionObjects();
    void processAreaFadeGroupAction(cocos2d::CCArray*, EnterEffectInstance*, cocos2d::CCPoint, bool);
    void processAreaMoveGroupAction(cocos2d::CCArray*, EnterEffectInstance*, cocos2d::CCPoint, int, int, int, int, int, bool, bool);
    void processAreaTintGroupAction(cocos2d::CCArray*, EnterEffectInstance*, cocos2d::CCPoint, bool);
    void processPlayerFollowActions(float);
    void processQueuedAudioTriggers();
    void triggerAreaEffectAnimation(EnterEffectObject*);
    void clearActivatedAudioTriggers();
    void controlDynamicRotateCommand(EffectGameObject*, int, GJActionCommand);
    void processAdvancedFollowAction(AdvancedFollowInstance&, bool, float);
    void processDynamicObjectActions(int, float);
    void triggerDynamicRotateCommand(EnhancedTriggerObject*);
    void updatePlayerCollisionBlocks();
    void activateObjectControlTrigger(ObjectControlGameObject*);
    void activatePlatformerEndTrigger(EndTriggerGameObject*, std::vector<int> const&);
    void activatePlayerControlTrigger(PlayerControlGameObject*);
    void controlAdvancedFollowCommand(AdvancedFollowTriggerObject*, int, GJActionCommand);
    void controlTriggersWithControlID(int, GJActionCommand);
    void processAdvancedFollowActions(float);
    void processAreaRotateGroupAction(cocos2d::CCArray*, EnterEffectInstance*, cocos2d::CCPoint, int, int, int, int, int, bool, bool);
    void regenerateEnterEasingBuffers();
    void triggerAdvancedFollowCommand(AdvancedFollowTriggerObject*);
    void updateDisabledObjectsLastPos(cocos2d::CCArray*);
    void updateProximityVolumeEffects();
    void updateStaticCameraPosToGroup(int, bool, bool, bool, float, float, int, float, bool, float);
    void activatePersistentItemTrigger(ItemTriggerGameObject*);
    void checkCameraLimitAfterTeleport(PlayerObject*, float);
    void processActivatedAudioTriggers(float);
    void restoreDefaultGameplayOffsetX();
    void restoreDefaultGameplayOffsetY();
    void processAreaTransformGroupAction(cocos2d::CCArray*, EnterEffectInstance*, cocos2d::CCPoint, int, int, int, int, int, bool, bool);
    void triggerAdvancedFollowEditCommand(AdvancedFollowEditObject*);
    void init() override;
    void visit();
    void update(float) override;
    void flipArt(bool);
    void hasItem(int);
    void getGroup(int);
    void testTime();
    void addPoints(int);

protected:
    bool m_activeOrderSpawnObjects;
    float m_cameraY;
    std::string m_capacityString;
    GJEffectManager* m_effectManager;
    std::string m_enterEasingKey;
    float m_followSpeedVal;
    cocos2d::CCArray* m_gameObjects;
    float m_gameTime;
    std::string m_groupParentsString;
    cocos2d::CCArray** m_groups;
    std::string m_particleKey;
    std::string m_particleKey2;
    PlayerObject* m_player1;
    PlayerObject* m_player2;
    int m_playerButtonID;
    std::string m_recordString;
    cocos2d::CCPoint m_savedPosition;
    float m_scaledGroundHeight;
    cocos2d::CCArray* m_sections;
    std::string m_specialKey;
    float m_timeMod;

};

#endif // GJBASEGAMELAYER_H_
