// ============================================================
// PlayerObject.h — Reconstructed from libcocos2dcpp.so
// Part of Geometry Dash v2.2.144 decompilation project
// ============================================================

#ifndef PLAYEROBJECT_H_
#define PLAYEROBJECT_H_

#include "GameObject.h"
#include "cocos2d.h"
#include <string>

// Forward declarations
class GameObject;

class PlayerObject : public GameObject {
public:
    virtual ~PlayerObject();
    virtual ~PlayerObject();
    virtual ~PlayerObject();

    void bumpPlayer(float, int, bool, GameObject*);
    void buttonDown(PlayerButton);
    void didHitHead();
    void isSafeFlip(float);
    void isSafeMode(float);
    void lockPlayer();
    void pushButton(PlayerButton);
    void pushPlayer(float);
    void reverseMod();
    void setOpacity(unsigned char);
    void setVisible(bool);
    void updateJump(float);
    void updateMove(float);
    void yStartDown();
    void boostPlayer(float);
    void createRobot(int);
    void flashPlayer(float, float, cocos2d::_ccColor3B, cocos2d::_ccColor3B);
    void flipGravity(bool, bool);
    void gravityDown();
    void resetObject();
    void resetStreak();
    void setPosition(cocos2d::CCPoint const&);
    void setRotation(float);
    void setupStreak();
    void spawnCircle();
    void stopDashing();
    void stopStreak2();
    void createSpider(int);
    void getYVelocity();
    void isBoostValid(float);
    void preCollision();
    void redirectDash(float);
    void setYVelocity(double, int);
    void spawnCircle2();
    void startDashing(DashRingObject*);
    void stopRotation(bool, int);
    void getActiveMode();
    void isInBasicMode();
    void levelFlipping();
    void levelWillFlip();
    void modeDidChange();
    void postCollision(float, bool);
    void propellPlayer(float, bool, int);
    void releaseButton(PlayerButton);
    void reversePlayer(EffectGameObject*);
    void stopParticles();
    void switchedDirTo(PlayerButton);
    void testForMoving(float, GameObject*);
    void toggleFlyMode(bool, bool);
    void touchedObject(GameObject*);
    void updateCollide(PlayerCollisionDirection, GameObject*);
    void updateDashArt();
    void updateEffects(float);
    void updateSpecial(float);
    void updateStreaks(float);
    void updateTimeMod(float, bool);
    void activateStreak();
    void addToYVelocity(double, int);
    void copyAttributes(PlayerObject*);
    void fadeOutStreak2(float);
    void getOldPosition(float);
    void getOrientedBox();
    void getSecondColor();
    void incrementJumps();
    void isInNormalMode();
    void isSafeHeadTest();
    void playBumpEffect(int, GameObject*);
    void rotateGameplay(int, int, bool, float, float, bool, bool);
    void setSecondColor(cocos2d::_ccColor3B const&);
    void spiderTestJump(bool);
    void storeCollision(PlayerCollisionDirection, int);
    void switchedToMode(GameObjectType);
    void toggleBirdMode(bool, bool);
    void toggleDartMode(bool, bool);
    void toggleRollMode(bool, bool);
    void updateRotation(float);
    void updateRotation(float, float);
    void addAllParticles();
    void doReversePlayer(bool);
    void getRealPosition();
    void hardFlipGravity();
    void hitGroundNoJump(GameObject*, bool);
    void playBurstEffect();
    void playDeathEffect();
    void playSpawnEffect();
    void playerDestroyed(bool);
    void playerIsFalling(float);
    void resetPlayerIcon();
    void runBallRotation(float);
    void runRotateAction(bool, int);
    void spawnDualCircle();
    void spawnFromPlayer(PlayerObject*, bool);
    void spiderTestJumpX(bool);
    void spiderTestJumpY(bool);
    void stopBurstEffect();
    void toggleRobotMode(bool, bool);
    void toggleSwingMode(bool, bool);
    void updateGlowColor();
    void updatePlayerArt();
    void updateSwingFire();
    void canStickToGround();
    void deactivateStreak(bool);
    void disableSwingFire();
    void isSafeSpiderFlip(float);
    void placeStreakPoint();
    void playerIsMovingUp();
    void playerTeleported();
    void playingEndEffect();
    void runBallRotation2();
    void saveToCheckpoint(PlayerCheckpoint*);
    void spawnScaleCircle();
    void specialGroundHit();
    void toggleSpiderMode(bool, bool);
    void toggleVisibility(bool);
    void updateCollideTop(float, GameObject*);
    void updatePlayerGlow();
    void addToTouchedRings(RingObject*);
    void animationFinished(char const*);
    void collidedWithSlope(float, GameObject*, bool);
    void getObjectRotation();
    void levelFlipFinished();
    void limitDashRotation(float&);
    void performSlideCheck();
    void preSlopeCollision(float, GameObject*);
    void releaseAllButtons();
    void resetAllParticles();
    void resetCollisionLog(bool);
    void resetTouchedRings(bool);
    void runNormalRotation(bool, float);
    void runNormalRotation();
    void spawnPortalCircle(cocos2d::_ccColor3B, float);
    void toggleGhostEffect(GhostType);
    void togglePlayerScale(bool, bool);
    void updateCollideLeft(float, GameObject*);
    void updatePlayerForce(cocos2d::CCPoint, bool);
    void updatePlayerFrame(int);
    void updatePlayerScale();
    void updateStaticForce(float, float, bool);
    void updateStreakBlend(bool);
    void collidedWithObject(float, GameObject*);
    void collidedWithObject(float, GameObject*, cocos2d::CCRect, bool);
    void deactivateParticle();
    void destroyFromHitHead();
    void gameEventTriggered(int, int);
    void loadFromCheckpoint(PlayerCheckpoint*);
    void playCompleteEffect(bool, bool);
    void removeAllParticles();
    void rotateGameplayOnly(bool);
    void tryPlaceCheckpoint();
    void updateCollideRight(float, GameObject*);
    void updateShipRotation(float);
    void getCurrentXVelocity();
    void handlePlayerCommand(int);
    void redirectPlayerForce(float, float, float, float);
    void resetStateVariables();
    void updateCollideBottom(float, GameObject*);
    void updateDashAnimation();
    void updateJumpVariables();
    void updateSlopeRotation(float);
    void enablePlayerControls();
    void getModifiedSlopeYVel();
    void playDynamicSpiderRun();
    void playSpiderDashEffect(cocos2d::CCPoint, cocos2d::CCPoint);
    void resetCollisionValues();
    void rotateGameplayObject(GameObject*);
    void togglePlatformerMode(bool);
    void updateCheckpointMode(bool);
    void updateCheckpointTest();
    void updateSlopeYVelocity(float);
    void updateStateVariables();
    void usingWallLimitedMode();
    void animatePlatformerJump(float);
    void checkSnapJumpToObject(GameObject*);
    void disablePlayerControls();
    void enableCustomGlowColor(cocos2d::_ccColor3B const&);
    void playerIsFallingBugged();
    void rotatePreSlopeObjects();
    void updateInternalActions(float);
    void updatePlayerBirdFrame(int);
    void updatePlayerDartFrame(int);
    void updatePlayerRollFrame(int);
    void updatePlayerShipFrame(int);
    void updateShipSpriteExtra(std::string);
    void disableCustomGlowColor();
    void removePlacedCheckpoint();
    void spiderTestJumpInternal(bool);
    void unrotateGameplayObject(GameObject*);
    void updateLastGroundObject(GameObject*);
    void updatePlayerRobotFrame(int);
    void updatePlayerSwingFrame(int);
    void createFadeOutDartStreak();
    void removePendingCheckpoint();
    void unrotatePreSlopeObjects();
    void updatePlayerSpiderFrame(int);
    void updatePlayerSpriteExtra(std::string);
    void convertToClosestRotation(float);
    void updatePlayerJetpackFrame(int);
    void collidedWithSlopeInternal(float, GameObject*, bool);
    void exitPlatformerAnimateJump();
    void updateRobotAnimationSpeed();
    void collidedWithObjectInternal(float, GameObject*, cocos2d::CCRect, bool);
    void handleRotatedSlopeCollision(float, GameObject*, bool);
    void stopPlatformerJumpAnimation();
    void handleRotatedObjectCollision(float, GameObject*, cocos2d::CCRect, bool);
    void handleRotatedCollisionInternal(float, GameObject*, cocos2d::CCRect, bool, bool, bool);
    void init(int, int, GJBaseGameLayer*, cocos2d::CCLayer*, bool) override;
    void create(int, int, GJBaseGameLayer*, cocos2d::CCLayer*, bool);
    void update(float) override;
    void flipMod();
    void speedUp();
    void isFlying();
    void pushDown();
    void ringJump(RingObject*, bool);
    void setColor(cocos2d::_ccColor3B const&);
    void setFlipX(bool);
    void setFlipY(bool);
    void setScale(float);
    void yStartUp();
    void gravityUp();
    void hitGround(GameObject*, bool);
    void logValues();
    void setScaleX(float);
    void setScaleY(float);
    void speedDown();

protected:
    bool m_activeMode;
    GameObject* m_activePortal;
    int m_bufferStates;
    cocos2d::_ccColor3B m_color;
    float m_gravity;
    IconType m_iconType;
    bool m_isDashing;
    bool m_isDead;
    bool m_isInPlayMode;
    bool m_isOnGround;
    bool m_isRising;
    float m_jumpHeight;
    cocos2d::CCPoint m_oldPosition;
    float m_playerSpeed;
    cocos2d::CCPoint m_position;
    cocos2d::CCPoint m_realPosition;
    float m_rotationSpeed;
    float m_scale;
    float m_scaleX;
    float m_scaleY;
    cocos2d::_ccColor3B m_secondColor;
    float m_vehicleSize;
    bool m_visible;
    float m_yVelocity;

};

#endif // PLAYEROBJECT_H_
