package com.robtopx.geometryjump;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class drawable {
        public static final int icon = 0x7f020000;
    }

    public static final class string {
        public static final int app_name = 0x7f030000;
    }
}
