#!/usr/bin/env python3
"""Generate Resources/RESOURCE_MANIFEST.md and Resources/SPRITE_FRAMES.md
for the Hieu Dash project, based on:
  1. What's currently in Resources/
  2. What resource references appear in gd_reference/src/*.cpp
  3. What sprite-frame names appear in gd_reference/src/ObjectToolbox.cpp
     (which contains the canonical GD 1.0 object → frame-name registry)
"""
import os
import re
from pathlib import Path

HIEU_ROOT = Path("/home/z/my-project/repos/HieuDash")
RES_DIR = HIEU_ROOT / "Resources"
GD_SRC = HIEU_ROOT / "gd_reference" / "src"
GD_HEADERS = HIEU_ROOT / "gd_reference" / "headers"

# --- 1. List existing resources ---
existing = sorted(p.name for p in RES_DIR.iterdir() if p.is_file())

# --- 2. Scan GD code for resource references ---
# Match: "filename.ext" where ext in {png,mp3,ogg,fnt,plist,wav}
res_pattern = re.compile(r'"([A-Za-z0-9_\-]+\.(?:png|mp3|ogg|fnt|plist|wav))"')
referenced = {}
for src in list(GD_SRC.rglob("*.cpp")) + list(GD_HEADERS.rglob("*.h")):
    try:
        text = src.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        continue
    for m in res_pattern.finditer(text):
        ref = m.group(1)
        referenced.setdefault(ref, []).append(src.relative_to(HIEU_ROOT))

# --- 3. Categorize ---
# Distinguish standalone file refs from sprite-frame names:
#  * Standalone files are referenced via CCSprite::create("X.png") etc.
#  * Sprite-frame names are referenced via CCSpriteFrameCache / createWithSpriteFrameName.
# Heuristic: known standalone sprite-sheet PNGs that ship as files
KNOWN_STANDALONE_PNGS = {
    "GJ_GameSheet.png", "GJ_GameSheet-hd.png",
    "GJ_GameSheet02.png", "GJ_GameSheet02-hd.png",
    "GJ_LaunchSheet.png", "GJ_LaunchSheet-hd.png",
    "GameSheetGlow.png", "GameSheetGlow-hd.png",
    "FireSheet_01.png", "FireSheet_01-hd.png",
    "GJ_square01.png", "GJ_square01-hd.png",
    "GJ_button_01.png", "GJ_button_01-hd.png",
    "GJ_button_02.png", "GJ_button_02-hd.png",
    "GJ_button_03.png", "GJ_button_03-hd.png",
    "GJ_button_04.png", "GJ_button_04-hd.png",
    "GJ_gradientBG.png", "GJ_gradientBG-hd.png",
    "GJ_progressBar_001.png", "GJ_progressBar_001-hd.png",
    "GJ_moveBtn.png", "GJ_moveBtn-hd.png",
    "GJ_moveSBtn.png", "GJ_moveSBtn-hd.png",
    "bigFont.png", "bigFont-hd.png",
    "chatFont.png", "chatFont-hd.png",
    "goldFont.png", "goldFont-hd.png",
}
known_audio = {
    "StereoMadness.mp3", "BackOnTrack.mp3", "Polargeist.mp3",
    "DryOut.mp3", "BaseAfterBase.mp3", "CantLetGo.mp3",
    "Jumper.mp3", "TimeMachine.mp3", "Cycles.mp3",
    "xStep.mp3", "Clutterfunk.mp3", "TheoryOfEverything.mp3",
    "Electroman.mp3", "Clubstep.mp3", "HexagonForce.mp3",
    "menuLoop.mp3", "StayInsideMe.mp3",
    "playSound_01.ogg", "endStart_02.ogg", "explode_11.ogg",
    "quitSound_01.ogg", "achievement_01.ogg",
    "playSound_01-hd.ogg", "endStart_02-hd.ogg",
}

# --- 4. Build manifest ---
existing_set = set(existing)
missing_standalone = []
sprite_frame_refs = []
missing_audio = []
for ref in sorted(referenced.keys()):
    if ref in existing_set:
        # already present, skip from missing lists but mention in sprite frame section
        if ref.endswith(".png") and ref not in KNOWN_STANDALONE_PNGS:
            sprite_frame_refs.append(ref)
        continue
    if ref.endswith(".png"):
        if ref in KNOWN_STANDALONE_PNGS:
            missing_standalone.append(ref)
        else:
            sprite_frame_refs.append(ref)
    elif ref.endswith((".mp3", ".ogg", ".wav")):
        if ref not in known_audio:
            missing_audio.append(ref)

# --- 5. Generate RESOURCE_MANIFEST.md ---
manifest_path = RES_DIR / "RESOURCE_MANIFEST.md"
with manifest_path.open("w", encoding="utf-8") as f:
    f.write("# Resources Manifest (v0.4)\n\n")
    f.write("Auto-generated by `scripts/gen_resource_manifest.py`. Enumerates every\n")
    f.write("resource file referenced by Hieu Dash C++ code (via the GD-Decompiled\n")
    f.write("reference snapshot in `gd_reference/`) and whether it is currently\n")
    f.write("present in this `Resources/` directory.\n\n")
    f.write("## Summary\n\n")
    f.write(f"- Total files in `Resources/`: **{len(existing)}**\n")
    f.write(f"- Unique resource names referenced in code: **{len(referenced)}**\n")
    f.write(f"- Standalone PNG files referenced but missing: **{len(missing_standalone)}**\n")
    f.write(f"- Audio files referenced but missing: **{len(missing_audio)}**\n")
    f.write(f"- Sprite-frame names referenced (loaded from sprite sheets, not standalone files): **{len(sprite_frame_refs)}**\n\n")

    f.write("## Currently shipped resources\n\n")
    f.write("These files are present in `Resources/` and are ready to be loaded by\n")
    f.write("the game:\n\n")
    for name in existing:
        f.write(f"- `{name}`\n")
    f.write("\n")

    f.write("## Missing standalone sprite sheets\n\n")
    f.write("These are **standalone PNG sprite-sheet files** referenced via\n")
    f.write("`CCSprite::create(\"…\")` or `CCSpriteFrameCache::addSpriteFramesWithFile(\"…\")`\n")
    f.write("in the GD 1.0 code, but NOT present in `Resources/`. They must be\n")
    f.write("extracted from the original Geometry Dash 1.0 APK (`assets/Resources/`)\n")
    f.write("and dropped into this directory.\n\n")
    if missing_standalone:
        for name in missing_standalone:
            f.write(f"- `{name}`\n")
    else:
        f.write("(none — all standalone sprite sheets are present)\n")
    f.write("\n")

    f.write("## Missing audio files\n\n")
    f.write("These audio files are referenced via `SimpleAudioEngine::playBackgroundMusic`\n")
    f.write("or `preloadEffect` in the GD 1.0 code, but NOT present in `Resources/`.\n")
    f.write("They must be extracted from the original Geometry Dash 1.0 APK\n")
    f.write("(`assets/Resources/`) and dropped into this directory.\n\n")
    if missing_audio:
        for name in missing_audio:
            f.write(f"- `{name}`\n")
    else:
        f.write("(none — all referenced audio files are present)\n")
    f.write("\n")

    f.write("## Sprite frame names (loaded from sprite sheets)\n\n")
    f.write("These are **sprite-frame names** referenced via\n")
    f.write("`CCSprite::createWithSpriteFrameName(\"…\")`. They are NOT standalone\n")
    f.write("PNG files — they are frames defined inside `GJ_GameSheet.plist`,\n")
    f.write("`GJ_GameSheet02.plist`, `GJ_LaunchSheet.plist`, `GameSheetGlow.plist`,\n")
    f.write("or `FireSheet_01.plist`. As long as the corresponding `.plist` + `.png`\n")
    f.write("pair is loaded into the `CCSpriteFrameCache`, these frames are\n")
    f.write("available at runtime.\n\n")
    f.write("These names are listed here so level designers and modders can look\n")
    f.write("up the exact frame ID for any GD 1.0 object.\n\n")
    for name in sprite_frame_refs[:50]:
        f.write(f"- `{name}`\n")
    if len(sprite_frame_refs) > 50:
        f.write(f"- … and {len(sprite_frame_refs) - 50} more (see SPRITE_FRAMES.md for the full list)\n")
    f.write("\n")

    f.write("## How to fill the gaps\n\n")
    f.write("1. Obtain the original Geometry Dash 1.0 APK\n")
    f.write("   (`com.robtopx.geometryjump`, August 2013 build).\n")
    f.write("2. Extract it with `apktool d GeometryDash.apk`.\n")
    f.write("3. Copy every file from `assets/Resources/` into this directory.\n")
    f.write("4. Re-run `python3 scripts/gen_resource_manifest.py` to verify the\n")
    f.write("   missing-file lists above are now empty.\n")
    f.write("5. Rebuild the project (`./proj.android/build_native.sh`).\n\n")
    f.write("> **Note:** the GD-Decompiled reference repo does NOT ship any\n")
    f.write("> binary assets — it is purely a code reference. So the missing\n")
    f.write("> files above cannot be copied from `gd_reference/`; they must be\n")
    f.write("> sourced from the original APK.\n")

print(f"Wrote {manifest_path}")
print(f"  Existing resources: {len(existing)}")
print(f"  Missing standalone PNGs: {len(missing_standalone)}")
print(f"  Missing audio: {len(missing_audio)}")
print(f"  Sprite frame refs (non-standalone): {len(sprite_frame_refs)}")

# --- 6. Generate SPRITE_FRAMES.md (full list) ---
frames_path = RES_DIR / "SPRITE_FRAMES.md"
with frames_path.open("w", encoding="utf-8") as f:
    f.write("# Sprite Frame Names (v0.4)\n\n")
    f.write("Complete list of every sprite-frame name referenced by Hieu Dash C++\n")
    f.write("code, sourced from the GD-Decompiled reference snapshot in\n")
    f.write("`gd_reference/src/`. These names are passed to\n")
    f.write("`CCSprite::createWithSpriteFrameName(\"…\")` at runtime and are resolved\n")
    f.write("against frames defined inside the following sprite-sheet `.plist` files:\n\n")
    f.write("- `GJ_GameSheet.plist` (loaded by `GJBaseGameLayer::init`)\n")
    f.write("- `GJ_GameSheet02.plist` (loaded by `GJBaseGameLayer::init` — **missing**, see RESOURCE_MANIFEST.md)\n")
    f.write("- `GJ_LaunchSheet.plist` (loaded by `AppDelegate::applicationDidFinishLaunching`)\n")
    f.write("- `GameSheetGlow.plist` (**missing**, see RESOURCE_MANIFEST.md)\n")
    f.write("- `FireSheet_01.plist` (**missing**, see RESOURCE_MANIFEST.md)\n\n")
    f.write("Frame names are grouped by their primary in-game object family.\n\n")
    # group by prefix
    groups = {}
    for name in sprite_frame_refs:
        prefix = name.split("_")[0] if "_" in name else "misc"
        groups.setdefault(prefix, []).append(name)
    for prefix in sorted(groups.keys()):
        f.write(f"## `{prefix}_…` ({len(groups[prefix])} frames)\n\n")
        for name in sorted(groups[prefix]):
            f.write(f"- `{name}`\n")
        f.write("\n")

print(f"Wrote {frames_path}")
